import { useState, useEffect } from "react";
import { translateFoodName } from "./food-translator";

export type Language = "pt" | "en" | "fr";

export const SUPPORTED_LANGUAGES: { id: Language; code: Language; label: string; flag: string }[] =
  [
    { id: "pt", code: "pt", label: "Português", flag: "🇵🇹" },
    { id: "en", code: "en", label: "English", flag: "🇬🇧" },
    { id: "fr", code: "fr", label: "Français", flag: "🇫🇷" },
  ];

export const NUTRITION_TIPS_MULTILANG = {
  pt: [
    "Beba água antes das refeições para auxiliar na digestão e aumentar a sensação de saciedade.",
    "Priorize alimentos inteiros e minimamente processados em vez de ultraprocessados e empacotados.",
    "Mastigue devagar: o cérebro leva cerca de 20 minutos para perceber que você está satisfeito.",
    "Inclua fontes de fibras saudáveis como aveia, chia ou linhaça no seu pequeno-almoço.",
    "Adicione cor ao seu prato: diferentes cores nas verduras indicam uma maior variedade de nutrientes e antioxidantes.",
    "A gordura boa faz bem! Consuma fontes saudáveis como abacate, azeite virgem extra e frutos secos com moderação.",
    "Evite açúcar refinado e refrigerantes; prefira sumos naturais de fruta diluídos ou águas aromatizadas.",
    "A proteína é essencial para a massa muscular e saciedade. Garanta uma porção nas suas refeições principais.",
    "Substitua os cereais refinados (como arroz branco e massas tradicionais) pelas suas versões integrais.",
    "Não confunda sede com fome: quando sentir um desejo repentino, beba um copo de água primeiro.",
    "Prepare as suas próprias refeições sempre que possível para ter total controle sobre os ingredientes.",
    "A qualidade do sono afeta a regulação do apetite e hormonas de saciedade. Durma pelo menos 7 a 8 horas.",
    "Evite comer a assistir televisão ou a mexer no telemóvel: a distração sabota a percepção de saciedade.",
    "Planeie as suas refeições da semana para evitar escolhas impulsivas e compras desnecessárias no supermercado.",
  ],
  en: [
    "Drink water before meals to assist digestion and increase your sense of fullness.",
    "Prioritize whole, minimally processed foods over ultra-processed and packaged products.",
    "Chew slowly: it takes your brain about 20 minutes to register that you are full.",
    "Include healthy fiber sources like oats, chia seeds, or flaxseed in your breakfast.",
    "Add color to your plate: diverse vegetable colors reflect a wider variety of nutrients and antioxidants.",
    "Healthy fats are beneficial! Consume avocado, extra virgin olive oil, and nuts in moderation.",
    "Limit refined sugars and sodas; choose infused water or naturally diluted fruit juices.",
    "Protein is vital for muscle maintenance and satiety. Include a portion in your main meals.",
    "Swap refined grains (like white rice and standard pasta) for their whole grain counterparts.",
    "Do not confuse thirst with hunger: when a sudden craving strikes, drink a glass of water first.",
    "Cook your own meals whenever possible to maintain full control over ingredients and sodium.",
    "Sleep quality directly impacts appetite hormones. Aim for 7 to 8 hours of restorative sleep.",
    "Avoid eating while watching TV or scrolling your phone: distractions hinder fullness cues.",
    "Plan your meals for the week to prevent impulsive snacking and unnecessary grocery buys.",
  ],
  fr: [
    "Buvez de l'eau avant les repas pour faciliter la digestion et accroître la satiété.",
    "Privilégiez les aliments bruts et peu transformés plutôt que les produits ultra-transformés.",
    "Mangez lentement : le cerveau met environ 20 minutes à enregistrer la sensation de satiété.",
    "Intégrez des fibres saines comme l'avoine, le chia ou le lin dans votre petit-déjeuner.",
    "Colorez votre assiette : la diversité des couleurs végétales garantit un large apport d'antioxydants.",
    "Les bons lipides sont précieux ! Consommez avocat, huile d'olive vierge et fruits à coque avec modération.",
    "Évitez les sucres raffinés et sodas ; préférez des eaux infusées ou des jus naturels dilués.",
    "Les protéines sont essentielles pour la masse musculaire et la satiété à chaque repas.",
    "Remplacez les féculents raffinés (riz blanc, pâtes classiques) par des versions complètes.",
    "Ne confondez pas soif et faim : face à une envie soudaine, buvez d'abord un verre d'eau.",
    "Cuisinez vous-même autant que possible pour contrôler la qualité des ingrédients et le sel.",
    "Un sommeil de qualité régule les hormones de l'appétit. Dormez entre 7 et 8 heures par nuit.",
    "Évitez de manger devant les écrans : la distraction fausse les signaux de satiété.",
    "Planifiez vos menus de la semaine pour éviter les achats impulsifs et le grignotage.",
  ],
};

export const translations = {
  pt: {
    common: {
      appName: "Sar scan",
      loading: "Carregando...",
      save: "Salvar",
      cancel: "Cancelar",
      confirm: "Confirmar",
      error: "Erro",
      success: "Sucesso",
      back: "Voltar",
      close: "Fechar",
      search: "Buscar",
      delete: "Excluir",
      edit: "Editar",
      continue: "Continuar",
      finish: "Concluir",
      yes: "Sim",
      no: "Não",
      or: "ou",
      all: "Todos",
      optional: "Opcional",
      required: "Obrigatório",
      retry: "Tentar novamente",
      copy: "Copiar",
      copied: "Copiado!",
      active: "Ativo",
      inactive: "Inativo",
      upgrade: "Fazer Upgrade",
      details: "Detalhes",
      viewAll: "Ver todos",
      none: "Nenhum",
      select: "Selecionar",
      share: "Compartilhar",
      day: "dia",
      week: "semana",
      month: "mês",
      year: "ano",
      kcal: "kcal",
      g: "g",
      ml: "ml",
      cm: "cm",
      kg: "kg",
      years: "anos",
    },
    nav: {
      scanner: "Scanner",
      search: "Buscar",
      shop: "Loja",
      profile: "Perfil",
      chat: "Sar IA",
      diary: "Diário",
    },
    auth: {
      loginTitle: "Alimente as suas metas",
      loginSubtitle: "Faça login para continuar gerenciando sua nutrição e saúde.",
      tabLogin: "ENTRAR",
      tabSignup: "Criar Conta",
      email: "E-mail",
      emailPlaceholder: "Seu e-mail de acesso",
      password: "Senha",
      passwordPlaceholder: "Insira sua senha",
      forgotPassword: "Esqueceu a senha?",
      forgotPasswordLink: "Esqueceu?",
      loginButton: "Entrar no Aplicativo",
      noAccount: "Não tem uma conta?",
      createAccount: "Criar conta",
      haveAccount: "Já tem uma conta?",
      signIn: "Entrar",
      signUpTitle: "Comece a sua jornada",
      signUpSubtitle: "Crie sua conta para escanear alimentos e transformar sua rotina.",
      name: "Nome Completo",
      namePlaceholder: "Seu nome e sobrenome",
      confirmPassword: "Confirmar Senha",
      confirmPasswordPlaceholder: "Repita a sua senha",
      signupButton: "Criar Minha Conta",
      termsAgreement: "Ao autenticar, você concorda com os nossos",
      termsLink: "Termos de Uso e Política de Privacidade",
      resetPasswordTitle: "Recuperar Acesso",
      resetPasswordSubtitle:
        "Informe seu e-mail cadastrado para enviarmos um link de redefinição de senha.",
      sendResetEmail: "Enviar Link de Recuperação",
      backToLogin: "Voltar para o Login",
      newPassword: "Nova Senha",
      updatePassword: "Redefinir Senha",
      welcomeBack: "Bem-vindo de volta!",
      accountCreated: "Conta criada com sucesso!",
      passwordsDoNotMatch: "As senhas não coincidem.",
      passwordTooShort: "A senha deve ter pelo menos 6 caracteres.",
      acceptTermsRequired: "Você precisa aceitar os termos de uso para continuar.",
      logoutConfirmTitle: "Sair da Conta",
      logoutConfirmDesc:
        "Tem certeza de que deseja sair? Você precisará entrar novamente na próxima vez.",
      logoutButton: "Sim, Sair",
      logoutCancel: "Cancelar",
    },
    onboarding: {
      title: "Vamos te conhecer",
      subtitle:
        "Informe seus dados básicos para calcularmos suas metas nutricionais diárias personalizadas.",
      measuresTitle: "Suas Medidas",
      age: "Idade",
      ageUnit: "anos",
      weight: "Peso",
      weightUnit: "kg",
      height: "Altura",
      heightUnit: "cm",
      objectiveTitle: "Escolha o seu Objetivo",
      loseWeight: "Perder Peso",
      loseWeightDesc: "Déficit moderado (-500 kcal/dia)",
      maintainWeight: "Manter Peso",
      maintainWeightDesc: "Equilíbrio calórico e manutenção",
      gainMuscle: "Ganhar Massa",
      gainMuscleDesc: "Superávit e hipertrofia (+300 kcal/dia)",
      submitButton: "Calcular Metas & Continuar",
      celebrationTitle: "Conseguiu a tempo! 🎉",
      celebrationSub:
        "Parabéns! O seu registo foi realizado durante o nosso período de campanha especial de boas-vindas. Ativámos bónus exclusivos na sua conta:",
      bonusScansTitle: "Scans de Alimentos Ativados",
      bonusScansDescPrefix: "Recebeu",
      bonusScansDescMid: "scans de bónus além dos 3 de oferta base. Começa com",
      bonusScansDescSuffix: "scans!",
      bonusChatTitle: "Acesso Gratuito ao Sar IA",
      bonusChatDescPrefix: "Desbloqueámos o Sar IA por",
      bonusChatDescSuffix:
        "dias grátis (até 30 mensagens diárias) para guiar a sua alimentação saudável!",
      claimCelebration: "Garantir Bónus & Definir Metas",
      fillAllFields: "Por favor, preencha todos os campos obrigatórios.",
      validAge: "Insira uma idade válida.",
      validWeight: "Insira um peso válido (kg).",
      validHeight: "Insira uma altura válida (cm).",
      goalsCalculated: "Metas calculadas com sucesso!",
      langSelect: "Idioma",
    },
    home: {
      greeting: "Olá",
      dailyGoal: "Meta Diária",
      caloriesToday: "Kcal de Hoje",
      caloriesEaten: "Consumidas",
      caloriesBurned: "Gasto",
      remaining: "Restantes",
      protein: "Proteínas",
      carbs: "Carboidratos",
      fats: "Gorduras",
      water: "Água",
      recentMeals: "Refeições Recentes",
      quickScan: "Escanear Prato",
      quickSearch: "Buscar Alimento",
      aiCoach: "Conversar com Sar IA",
      streak: "dias seguidos",
      waterGlass: "copo",
      waterGlasses: "copos",
      addWater: "Adicionar Água",
      todaySummary: "Resumo de Hoje",
      noMealsToday: "Nenhuma refeição registrada hoje.",
      clickToScan: "Toque para escanear seu prato com IA",
      suggestions: "Sugestões",
      viewAll: "Ver tudo",
      remainingScans: "Scans Restantes",
      tipOfDay: "Nutrição do Dia",
      healthyTip: "Dica Saudável",
      anotherTip: "Ver outra dica",
      tipMotto: "Viver melhor começa no prato",
    },
    scanner: {
      title: "Scanner Nutricional",
      instructions: "Aponte a câmera para o prato ou alimento",
      takePhoto: "Escanear Prato",
      gallery: "Galeria",
      uploadPhoto: "Carregar Foto",
      switchCamera: "Alternar Câmera",
      flash: "Lanterna",
      analyzing: "Analisando Alimento...",
      calibratingHand: "Usando calibração biométrica da mão para porções exatas",
      detectedFood: "Alimento detectado!",
      foodStatusReady: "Prato enquadrado",
      foodStatusScanning: "Ajustando foco...",
      foodStatusSearching: "Aponte para o alimento",
      remainingScans: "Scans restantes",
      unlimited: "Ilimitado",
      noScansLeft: "Você atingiu o limite de scans gratuitos.",
      unlockMore: "Desbloquear Mais Scans",
      handCalibratedBadge: "Escala Biométrica Ativa",
      handCalibratedDesc: "Coloque sua mão ao lado do prato para obter dados mais precisos.",
      adjust: "Ajustar",
      calibrateHandPrompt: "Quer dados e porções mais precisos?",
      calibrateHandDesc: "Calibre sua mão uma vez no perfil para ter medições com maior precisão.",
      calibrate: "Calibrar",
      portion: "Porção",
      addMealSuccess: "Refeição adicionada ao diário com sucesso!",
      confidence: "Confiança da IA",
      cameraDisabled: "Câmera Desabilitada",
      enableCamera: "Toque aqui para tentar reativar o acesso",
      switchCameraTitle: "Alternar câmera frontal/traseira",
    },
    shop: {
      title: "Loja & Planos Premium",
      subtitle: "Arquitetura de Inteligência Nutricional",
      weekly: "Semanal",
      monthly: "Mensal",
      yearly: "Anual",
      activePlan: "Plano Ativo",
      currentPlan: "Plano Atual",
      subscribeNow: "Assinar Agora",
      upgradePlan: "Upgrade de Plano",
      startTrial: "Ativar 7 Dias Grátis",
      trialButton: "Testar 7 Dias",
      trialActive: "Teste Gratuito Ativo",
      freeTrialBadge: "7 Dias Grátis",
      popularBadge: "Popular",
      bestValueBadge: "Melhor valor",
      cycleWeekly: "/semana",
      cycleMonthly: "/mês",
      cycleYearly: "/ano",
      hintWeekly: "Ideal para experimentar",
      hintMonthly: "Mais escolhido",
      hintYearly: "Economize ~58%",
      whyPremium: "Por que ser Premium?",
      benefitsTitle: "Escolha sua jornada",
      subStatus: "Status da Assinatura",
      statusActive: "Ativa",
      validUntil: "Válido até",
      cancelAnytime: "Renovação automática · Cancele quando quiser",
      trialCancelAnytime: "7 dias grátis · Cancele quando quiser",
      higherPlanActive: "Plano Superior Ativo",
      creditsPackTitle: "Pacotes de Créditos (Consumível)",
      credits50Title: "Pacote de 50 Scans",
      oneTimePayment: "/ pagamento único",
      credits50Desc:
        "Perfeito se você já atingiu o limite semanal ou mensal ou prefere não utilizar uma assinatura premium recorrente neste momento. Adiciona 50 scans definitivos ao seu utilizador.",
      buy50Scans: "Comprar 50 Scans",
      why1Title: "Scans com Super IA",
      why1Desc: "Identificação ultra detalhada e imediata",
      why2Title: "Nutricionista IA 24/7",
      why2Desc: "Tire dúvidas e peça receitas a qualquer hora",
      why3Title: "Análise de Sentimento",
      why3Desc: "Entendemos como sua dieta afeta seu humor",
      why4Title: "Metas Dinâmicas",
      why4Desc: "Ajuste seus objetivos conforme sua evolução",
      trialModalTitle: "Comece 7 dias grátis",
      trialModalSub:
        "Experimente todos os benefícios do plano {plan} totalmente grátis por {days} dias!",
      planPerksTitle: "Benefícios do plano:",
      totalToday: "Total Hoje",
      after7Days: "Após 7 dias",
      activateTrialBtn: "Ativar Teste Grátis",
      maybeLater: "Talvez depois",
      successTitle: "Plano Ativado com Sucesso!",
      successTrialTitle: "Teste Grátis Ativado!",
      successCreditsTitle: "50 Scans Adicionados!",
      successDesc:
        "Parabéns! Sua assinatura está confirmada e o acesso foi liberado em tempo real.",
      successTrialDesc: "Você tem 7 dias de acesso com créditos para escanear seus alimentos.",
      successCreditsDesc: "Os 50 scans foram creditados e já estão prontos para você utilizar.",
      accountDetails: "DETALHES DA SUA CONTA:",
      totalScansAvailable: "scans totais disponíveis",
      noExpiryCredits: "Créditos sem data de expiração",
      aiUnlocked: "Detecção e análise por IA liberada",
      startScanningNow: "Começar a escanear agora",
      openInApp: "Abrir no aplicativo Android instalado",
      trialCancelNote: "Cancele a qualquer momento no seu perfil se mudar de ideia.",
      activePerksNote: "Suas vantagens já estão ativas na sua conta.",
      pWeekly1: "30 scans / semana",
      pWeekly2: "Chat IA Nutricionista (50 mensagens)",
      pWeekly3: "Edição de metas",
      pWeekly4: "Suporte prioritário",
      pMonthly1: "150 scans / mês",
      pMonthly2: "Chat IA Nutricionista (50 mensagens / dia)",
      pMonthly3: "Edição de metas",
      pMonthly4: "Suporte prioritário",
      pMonthly5: "Histórico estendido",
      pYearly1: "1200 scans / ano",
      pYearly2: "Chat IA Nutricionista (150 mensagens / dia)",
      pYearly3: "Edição de metas",
      pYearly4: "Suporte prioritário",
      pYearly5: "Acesso antecipado",
    },
    profile: {
      title: "Perfil",
      editProfile: "Editar Perfil",
      adminPanel: "Painel de Administração",
      subscriptions: "Assinaturas",
      rewards: "Recompensas",
      history: "Histórico de Leitura",
      goals: "Metas Diárias",
      objective: "Objetivo",
      physicalData: "Dados Físicos",
      handCalibration: "Calibração da Mão (Alta Precisão)",
      changePassword: "Alterar Senha",
      notifications: "Notificações Push",
      notificationsSub: "Ativar alertas e lembretes diários",
      privacy: "Direitos e Privacidade",
      deleteAccount: "Excluir Conta",
      signOut: "Sair da Conta",
      language: "Idioma do Aplicativo",
      sectionSubscription: "Assinatura & Histórico",
      sectionGoals: "Metas & Dados Físicos",
      sectionPreferences: "Preferências & Lembretes",
      sectionSecurity: "Segurança & Conta",
      languageSelectorTitle: "Selecione o Idioma",
      chooseLanguage: "Escolha o idioma de sua preferência",
    },
    waterReminder: {
      title: "Lembretes de Hidratação",
      tag: "ÁGUA",
      subtitle: "Receba notificações diárias para lembrar de manter o corpo bem hidratado.",
      presetsTitle: "Presets de Horários",
      preset2h: "Cada 2 horas",
      preset3h: "Cada 3 horas",
      clearAll: "Limpar todos",
      scheduledTimes: "Seus Horários Agendados",
      emptySchedule: "Sem horários agendados. Adicione um abaixo!",
      addTime: "Adicionar Horário",
      timeInput: "Horário",
      addButton: "Adicionar",
      testButton: "Testar Notificações",
      testingNotification: "Disparando teste...",
      testSuccessToast: "Teste acionado! Verifique as suas notificações do telemóvel.",
      maxTimesReached: "Limite máximo de 10 horários alcançado.",
      timeAlreadyAdded: "Este horário já foi adicionado.",
      timeAddedToast: "Horário adicionado com sucesso.",
      timeRemovedToast: "Horário removido com sucesso.",
    },
    direitos: {
      title: "Direitos e Privacidade",
      termsTab: "Termos de Uso",
      privacyTab: "Política de Privacidade",
      copyLink: "Copiar Link",
      copied: "Copiado!",
      rightsTitle: "Termos de Uso e Condições Gerais",
      privacyTitle: "Política de Privacidade e Proteção de Dados",
      backToProfile: "Voltar",
      lastUpdated: "Última atualização: Setembro de 2026",
      terms: {
        introTitle: "1. Aceitação dos Termos",
        introText:
          "Ao acessar e utilizar o aplicativo Sar scan, você concorda expressamente em cumprir todos os termos e condições aqui estipulados. Caso não concorde com qualquer disposição, solicitamos que não utilize nossos serviços.",
        serviceTitle: "2. Descrição do Serviço",
        serviceText:
          "O Sar scan é uma plataforma de inteligência artificial aplicada ao reconhecimento visual e estimativa nutricional de alimentos, rastreamento de ingestão de água, calorias e macronutrientes.",
        disclaimerTitle: "3. Isenção de Responsabilidade Médica",
        disclaimerText:
          "O aplicativo Sar scan não substitui diagnósticos, prescrições ou tratamentos médicos ou nutricionais profissionais. Todas as informações fornecidas têm caráter exclusivamente informativo e educativo.",
        accountTitle: "4. Cadastro e Segurança da Conta",
        accountText:
          "Você é o único responsável pela veracidade dos dados cadastrados e pela confidencialidade de suas credenciais de acesso, devendo notificar imediatamente a equipe em caso de uso não autorizado.",
        ipTitle: "5. Propriedade Intelectual",
        ipText:
          "Todos os algoritmos, modelos de visão computacional, marcas, logotipos, interfaces gráficas e conteúdos presentes no Sar scan são de propriedade exclusiva de seus desenvolvedores e protegidos pela legislação internacional de direitos autorais.",
      },
      privacy: {
        introTitle: "1. Coleta e Uso de Dados",
        introText:
          "Coletamos dados fornecidos voluntariamente por você (como e-mail, idade, peso, altura, metas e fotos enviadas para escaneamento nutricional) com a finalidade exclusiva de prestar e aprimorar nossos serviços de IA.",
        processingTitle: "2. Processamento Visual e Biometria",
        processingText:
          "As imagens enviadas para escaneamento e calibração biométrica da mão são processadas por algoritmos seguros de visão computacional estritamente para estimar porções e nutrientes.",
        storageTitle: "3. Armazenamento e Criptografia",
        storageText:
          "Seus dados são armazenados em servidores com criptografia de ponta a ponta (AES-256 e SSL/TLS) e protegidos por regras rigorosas de segurança.",
        rightsTitle: "4. Seus Direitos de Privacidade (LGPD / GDPR)",
        rightsText:
          "Você possui o direito inalienável de solicitar a qualquer momento o acesso, a correção, a exportação ou a exclusão definitiva e irreversível de todos os seus dados e histórico através da opção Excluir Conta no painel de perfil.",
        contactTitle: "5. Encarregado de Proteção de Dados",
        contactText:
          "Para dúvidas ou solicitações referentes à sua privacidade e tratamento de dados, entre em contato diretamente com o nosso suporte através do canal oficial de atendimento no aplicativo.",
      },
    },
    editProfile: {
      title: "Editar Perfil",
      name: "Nome completo",
      email: "E-mail",
      save: "Salvar Alterações",
      success: "Perfil atualizado com sucesso",
      changePhoto: "Trocar Foto",
      uploading: "Enviando...",
    },
    subpages: {
      changePassword: {
        title: "Alterar Senha",
        cardTitle: "Segurança da conta",
        cardSub: "Use ao menos 6 caracteres",
        current: "Senha atual",
        new: "Nova senha",
        confirm: "Confirmar nova senha",
        button: "Atualizar Senha",
        success: "Senha atualizada com sucesso!",
      },
      rewards: {
        title: "Recompensas Bônus",
        subtitle: "Scans e créditos enviados pelo administrador",
        claim: "Resgatar Recompensa",
        claimed: "Resgatado",
        empty: "Nenhuma recompensa disponível no momento.",
        scansReward: "Scans Bônus de Presente",
      },
      subscriptions: {
        title: "Assinaturas",
        subtitle: "Gerencie seu plano atual e acesso premium",
        active: "Plano Ativo",
        upgrade: "Mudar para Premium",
        manage: "Gerenciar Assinatura",
        activeUntil: "Ativo até",
      },
      goals: {
        title: "Metas Diárias",
        subtitle: "Ajuste os valores de calorias e macronutrientes",
        calories: "Calorias Diárias (kcal)",
        protein: "Proteínas (g)",
        carbs: "Carboidratos (g)",
        fats: "Gorduras (g)",
        save: "Salvar Metas",
        success: "Metas salvas com sucesso!",
      },
      objective: {
        title: "Seu Objetivo",
        subtitle: "Selecione o seu objetivo nutricional principal",
        lose: "Perder Peso",
        loseDesc: "Déficit calórico para redução de gordura corporal",
        maintain: "Manter Peso",
        maintainDesc: "Equilíbrio calórico para manter peso e saúde",
        gain: "Ganhar Massa Muscular",
        gainDesc: "Superávit calórico focado em hipertrofia",
        save: "Salvar Objetivo",
        success: "Objetivo atualizado!",
      },
      physicalData: {
        title: "Dados Físicos",
        subtitle: "Atualize peso, altura e idade para recalcular suas metas",
        weight: "Peso (kg)",
        height: "Altura (cm)",
        age: "Idade (anos)",
        save: "Salvar Dados",
        success: "Dados físicos atualizados com sucesso!",
      },
      handCalibration: {
        title: "Calibração Biométrica da Mão",
        subtitle: "Medição de referência óptica para estimativa precisa de porções",
        introTitle: "Como Funciona a Calibração",
        introDesc:
          "A calibração da mão cria uma régua óptica personalizada. Ao posicionar sua mão ao lado do prato nas fotos, a IA compara o tamanho dos alimentos com suas medidas reais para calcular gramas e calorias com máxima precisão.",
        startBtn: "Iniciar Calibração",
        selectObjectTitle: "Escolha o Objeto de Referência",
        selectObjectDesc:
          "Selecione um objeto padrão que você tenha em mãos para calibrar as dimensões:",
        cardName: "Cartão (Crédito / Identidade)",
        cardDesc: "Tamanho padrão mundial (8,56 x 5,39 cm)",
        coinName: "Moeda (2 Euros / 1 Real)",
        coinDesc: "Diâmetro padrão (~2,57 cm)",
        sheetName: "Folha A4",
        sheetDesc: "Papel comum (21,0 x 29,7 cm)",
        nextStep: "Avançar para a Câmera",
        cameraGuideTitle: "Posicione a Mão e o Objeto",
        cameraGuideText:
          "Coloque a mão aberta com a palma para baixo e o objeto ao lado sobre uma superfície plana e bem iluminada.",
        captureBtn: "Capturar e Analisar",
        analyzingTitle: "Processando Biometria com IA...",
        analyzingDesc:
          "Detectando contornos da mão, nós dos dedos e escala milimétrica do objeto...",
        resultTitle: "Calibração Concluída com Sucesso!",
        resultDesc: "Sua escala biométrica personalizada já está ativa para todos os scans.",
        handLength: "Comprimento da Mão",
        palmWidth: "Largura da Palma",
        fingerWidth: "Largura do Indicador",
        confidence: "Índice de Confiança",
        recalibrateBtn: "Recalibrar Mão",
        backToProfile: "Voltar para o Perfil",
        errorTitle: "Não foi possível calibrar",
        retryBtn: "Tentar Novamente",
        tipsHeader: "Dicas para uma boa calibração:",
        tip1: "Mantenha a câmera perpendicular e sem inclinações.",
        tip2: "Certifique-se de que a mão e o objeto estão totalmente visíveis.",
        tip3: "Utilize um ambiente com boa iluminação e sem sombras fortes.",
      },
      deleteAccount: {
        title: "Excluir Conta",
        warning:
          "Esta ação é irreversível. Todos os seus dados e histórico serão apagados permanentemente.",
        confirmButton: "Sim, Excluir Minha Conta",
        confirmPrompt: "Digite a palavra 'EXCLUIR' para confirmar:",
      },
    },
    search: {
      title: "Buscar Alimento",
      subtitle: "Pesquise na base nutricional ou use a busca inteligente por IA",
      placeholder: "Digite o alimento ou prato...",
      aiSearch: "Analisar com IA",
      recent: "Buscas Recentes",
      popularFoods: "Alimentos Populares",
      noResults: "Nada encontrado. Use a busca por IA acima.",
      searching: "Buscando alimento...",
      addToDiary: "Adicionar ao Diário",
      portion: "Porção",
      loadMore: "Carregar mais ({count} restantes)",
      backToCategories: "← Voltar à lista por categorias",
      foodsCount: "{total} alimentos • {filtered}",
      categories: {
        all: "Todos",
        frutas: "Frutas",
        carnes: "Carnes & Aves",
        peixes: "Peixes & Frutos do Mar",
        ovos_laticinios: "Ovos & Queijos",
        paes_massas: "Pães, Arroz & Massas",
        saladas_legumes: "Saladas & Legumes",
        lanches: "Lanches & Pizzas",
        bebidas: "Bebidas & Shakes",
        doces: "Doces & Sobremesas",
      },
    },
    diario: {
      title: "Diário Alimentar",
      subtitle: "Acompanhe todo o seu consumo de calorias e macros",
      today: "Hoje",
      yesterday: "Ontem",
      history: "Histórico de Registros",
      emptyDay: "Nenhum alimento registrado neste dia.",
      totalDay: "Total do Dia",
      consumed: "Consumido",
      goal: "Meta",
      remaining: "Restante",
      protein: "Proteínas",
      carbs: "Carboidratos",
      fats: "Gorduras",
      water: "Água",
      calories: "Calorias",
      deleteConfirm: "Excluir Registro",
      deletePrompt: "Deseja realmente excluir este alimento do seu diário?",
      speakNutrients: "Ouvir Nutrientes",
      stopAudio: "Parar Áudio",
      mealDetails: "Detalhes da Refeição",
      portion: "Porção",
      savedAt: "Registrado às",
    },
    chat: {
      title: "Sar IA",
      subtitle: "Assistente e Especialista em Nutrição 24/7",
      statusOnline: "Online • Especialista em Nutrição",
      dailyUsage: "Uso Diário",
      unlimited: "Ilimitado",
      campaignActive: "Acesso de bónus ativo! Sar IA gratuito expira em:",
      campaignBadge: "CAMPANHA",
      exclusiveTitle: "Sar IA Exclusivo",
      exclusiveDesc:
        "Tenha um especialista em nutrição disponível 24 horas por dia para tirar dúvidas, calcular macros, analisar pratos e montar estratégias alimentares personalizadas.",
      exclusivePlans: "Disponível nos planos Semanal, Mensal e Anual",
      unlockPremium: "Ativar Acesso Premium",
      helloUser: "Olá, {name}! 👋",
      welcomeIntro:
        "Sou o Sar IA, seu assistente especialista em nutrição. Como posso ajudar com a sua alimentação e metas hoje?",
      analyzing: "Sar IA analisando...",
      placeholder: "Pergunte ao Sar IA ou envie foto do prato (PNG/JPEG)...",
      send: "Enviar",
      emptyTitle: "Como posso ajudar hoje?",
      emptySubtitle:
        "Tire dúvidas sobre sua alimentação, peça receitas saudáveis ou avalie seu plano nutricional.",
      clearChatTitle: "Limpar Histórico?",
      clearChatDesc: "Esta ação removerá todas as mensagens trocadas com o Sar IA.",
      clearConfirmBtn: "Apagar",
      clearChat: "Limpar Conversa",
      limitReachedTitle: "Limite Diário Atingido",
      limitReachedDesc:
        "Você utilizou todas as {limit} mensagens diárias do seu plano. O limite será reiniciado amanhã.",
      upgradeUnlimited: "Migrar para Anual (Ilimitado)",
      understood: "Entendido",
      planProposed: "Plano Nutricional Proposto",
      planGoal: "Meta:",
      planStrategy: "Dieta/Estratégia:",
      planAcceptedBadge: "✅ Plano Aceito e Aplicado ao Perfil",
      planRejectedBadge: "❌ Plano Recusado",
      acceptPlan: "Aceitar Plano",
      rejectPlan: "Recusar",
      planAppliedToast: "Plano nutricional aplicado com sucesso ao seu perfil!",
      planRejectedToast: "Plano nutricional recusado.",
      preset1: "O que posso comer no jantar leve?",
      preset2: "Quantas calorias tem um prato de arroz com frango?",
      preset3: "Dicas para bater a meta de proteínas",
      promptCalcMacrosTitle: "Calcular meus macros",
      promptCalcMacrosText:
        "Gostaria de calcular meus macronutrientes ideais para o meu objetivo atual.",
      promptWorkoutTitle: "Pré e pós-treino",
      promptWorkoutText:
        "Quais são as melhores opções de refeição para comer antes e depois do meu treino?",
      promptLunchTitle: "Almoço proteico",
      promptLunchText: "Me dê uma sugestão de almoço proteico, saudável e fácil de preparar.",
      promptFatLossTitle: "Dicas para secar",
      promptFatLossText:
        "Quais estratégias nutricionais você recomenda para queimar gordura mantendo massa magra?",
      imageFormatError: "Por favor, envie apenas imagens nos formatos PNG ou JPEG.",
      historyClearedSuccess: "Histórico da conversa limpo com sucesso.",
    },
    calibration: {
      title: "Calibração da Mão",
      subtitle: "Medição biométrica de alta precisão para porções exatas",
      howItWorks: "Como Funciona a Calibração",
      howItWorksDesc:
        "Sua mão serve como régua visual permanente. Ao registrar suas medidas reais com um objeto de referência, o Sar scan calibra os pixels de cada prato para estimar porções e nutrientes com precisão milimétrica.",
      step1Title: "Escolha um objeto de referência",
      step1Desc: "Cartão bancário/ID, moeda de 2€/1R$, tampa ou régua.",
      step2Title: "Posicione a mão e o objeto lado a lado",
      step2Desc: "Apoie a palma aberta numa mesa lisa e tire uma foto de cima para baixo.",
      step3Title: "Calibração Automática por IA",
      step3Desc: "Nosso algoritmo detecta os nós dos dedos, a palma e o tamanho em milímetros.",
      startCalibration: "Iniciar Calibração",
      selectObject: "Escolha o Objeto de Referência",
      selectObjectDesc: "Selecione o objeto que colocará ao lado da sua mão na foto:",
      tabAll: "Todos os Objetos",
      tabCards: "Cartões & Réguas",
      tabCoins: "Moedas & Pequenos",
      creditCard: "Cartão Bancário / ID / Fidelidade",
      creditCardDesc: "Qualquer cartão plástico padrão (crédito, débito, cidadão)",
      coin2eur: "Moeda de 2 Euros (€2)",
      coin2eurDesc: "Moeda padrão de 2 Euros comum na Europa (25,75 mm)",
      coin1real: "Moeda de 1 Real (R$ 1)",
      coin1realDesc: "Moeda padrão bimetálica de 1 Real (27,00 mm)",
      coin1eur: "Moeda de 1 Euro (€1)",
      coin1eurDesc: "Moeda padrão de 1 Euro (23,25 mm)",
      bottleCap: "Tampa de Garrafa Pet",
      bottleCapDesc: "Tampa plástica padrão de refrigerante ou água (28,00 mm)",
      ruler: "Régua ou Fita Métrica",
      rulerDesc: "Régua com marcação visível de centímetros (escala métrica)",
      photoTip: "Dica para a foto:",
      photoTipDesc: "Coloque a mão aberta e o objeto apoiados na mesa, paralelos à câmera.",
      openCamera: "Abrir Câmera",
      orUpload: "Ou enviar foto da galeria",
      cameraGuide: "Enquadre a mão aberta e o objeto na mesma foto",
      handGuide: "Mão Aberta",
      calculating: "Analisando Biometria da Mão...",
      calculatingDesc: "Calculando as dimensões exatas da palma, dedos e proporção óptica...",
      profileActive: "Escala Biométrica Ativa",
      scaleCalibrated: "Mão Calibrada com Sucesso!",
      accuracy: "Precisão Óptica",
      handLength: "Comprimento da Mão",
      wristToMiddleFinger: "Do punho até a ponta do dedo médio",
      palmWidth: "Largura da Palma",
      palmTransversal: "Largura transversal da palma",
      howToUseDaily: "Como usar nos scans diários",
      howToUseDailyDesc:
        "Ao fotografar seu prato, coloque a mão ao lado da comida. O Sar scan identificará a sua mão ({length} cm) e ajustará automaticamente o peso e as calorias com precisão!",
      goToScanner: "Ir para o Scanner",
      recalibrate: "Recalibrar",
      takeNewPhoto: "Tirar Nova Foto",
      sendGallery: "Enviar da Galeria",
      changeObject: "Trocar Objeto",
      errorTitle: "Verificação Incompleta",
      analyzedPhoto: "Foto analisada",
      analysisReason: "Motivo da Análise",
      analysisReasonDesc:
        "Não foi possível identificar com nitidez a mão e o objeto de referência na mesma imagem.",
      howToResolve: "Como resolver na próxima foto:",
      howToResolveDesc:
        "Certifique-se de apoiar a mão bem aberta ao lado do objeto numa superfície plana com boa iluminação.",
    },
  },
  en: {
    common: {
      appName: "Sar scan",
      loading: "Loading...",
      save: "Save",
      cancel: "Cancel",
      confirm: "Confirm",
      error: "Error",
      success: "Success",
      back: "Back",
      close: "Close",
      search: "Search",
      delete: "Delete",
      edit: "Edit",
      continue: "Continue",
      finish: "Finish",
      yes: "Yes",
      no: "No",
      or: "or",
      all: "All",
      optional: "Optional",
      required: "Required",
      retry: "Try again",
      copy: "Copy",
      copied: "Copied!",
      active: "Active",
      inactive: "Inactive",
      upgrade: "Upgrade",
      details: "Details",
      viewAll: "View all",
      none: "None",
      select: "Select",
      share: "Share",
      day: "day",
      week: "week",
      month: "month",
      year: "year",
      kcal: "kcal",
      g: "g",
      ml: "ml",
      cm: "cm",
      kg: "kg",
      years: "years",
    },
    nav: {
      scanner: "Scanner",
      search: "Search",
      shop: "Shop",
      profile: "Profile",
      chat: "Sar AI",
      diary: "Diary",
    },
    auth: {
      loginTitle: "Fuel your goals",
      loginSubtitle: "Log in to continue managing your nutrition and health.",
      tabLogin: "LOG IN",
      tabSignup: "Sign Up",
      email: "Email",
      emailPlaceholder: "Your email address",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      forgotPassword: "Forgot password?",
      forgotPasswordLink: "Forgot?",
      loginButton: "Log In to App",
      noAccount: "Don't have an account?",
      createAccount: "Create account",
      haveAccount: "Already have an account?",
      signIn: "Log In",
      signUpTitle: "Start your journey",
      signUpSubtitle: "Create your account to scan food and transform your routine.",
      name: "Full Name",
      namePlaceholder: "Your full name",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "Repeat your password",
      signupButton: "Create My Account",
      termsAgreement: "By continuing, you agree to our",
      termsLink: "Terms of Use and Privacy Policy",
      resetPasswordTitle: "Reset Password",
      resetPasswordSubtitle: "Enter your registered email to receive a password reset link.",
      sendResetEmail: "Send Reset Link",
      backToLogin: "Back to Login",
      newPassword: "New Password",
      updatePassword: "Reset Password",
      welcomeBack: "Welcome back!",
      accountCreated: "Account created successfully!",
      passwordsDoNotMatch: "Passwords do not match.",
      passwordTooShort: "Password must be at least 6 characters.",
      acceptTermsRequired: "You must accept the terms of use to continue.",
      logoutConfirmTitle: "Sign Out",
      logoutConfirmDesc:
        "Are you sure you want to sign out? You will need to log back in next time.",
      logoutButton: "Yes, Sign Out",
      logoutCancel: "Cancel",
    },
    onboarding: {
      title: "Let's get to know you",
      subtitle:
        "Provide your basic information so we can calculate your personalized daily nutritional targets.",
      measuresTitle: "Your Measurements",
      age: "Age",
      ageUnit: "years",
      weight: "Weight",
      weightUnit: "kg",
      height: "Height",
      heightUnit: "cm",
      objectiveTitle: "Choose your Goal",
      loseWeight: "Lose Weight",
      loseWeightDesc: "Moderate deficit (-500 kcal/day)",
      maintainWeight: "Maintain Weight",
      maintainWeightDesc: "Caloric balance and maintenance",
      gainMuscle: "Build Muscle",
      gainMuscleDesc: "Surplus and hypertrophy (+300 kcal/day)",
      submitButton: "Calculate Goals & Continue",
      celebrationTitle: "You made it in time! 🎉",
      celebrationSub:
        "Congratulations! Your registration qualified for our special welcome campaign. We've unlocked exclusive bonuses for your account:",
      bonusScansTitle: "Food Scans Activated",
      bonusScansDescPrefix: "You received",
      bonusScansDescMid: "bonus scans on top of your 3 base scans. You start with",
      bonusScansDescSuffix: "scans!",
      bonusChatTitle: "Free Sar AI Access",
      bonusChatDescPrefix: "We unlocked Sar AI for",
      bonusChatDescSuffix: "free days (up to 30 daily messages) to guide your healthy eating!",
      claimCelebration: "Claim Bonus & Set Goals",
      fillAllFields: "Please fill in all required fields.",
      validAge: "Please enter a valid age.",
      validWeight: "Please enter a valid weight (kg).",
      validHeight: "Please enter a valid height (cm).",
      goalsCalculated: "Goals calculated successfully!",
      langSelect: "Language",
    },
    home: {
      greeting: "Hello",
      dailyGoal: "Daily Target",
      caloriesToday: "Today's Kcal",
      caloriesEaten: "Consumed",
      caloriesBurned: "Burned",
      remaining: "Remaining",
      protein: "Protein",
      carbs: "Carbs",
      fats: "Fats",
      water: "Water",
      recentMeals: "Recent Meals",
      quickScan: "Scan Meal",
      quickSearch: "Search Food",
      aiCoach: "Chat with Sar AI",
      streak: "day streak",
      waterGlass: "glass",
      waterGlasses: "glasses",
      addWater: "Add Water",
      todaySummary: "Today's Summary",
      noMealsToday: "No meals logged yet today.",
      clickToScan: "Tap to scan your plate with AI",
      suggestions: "Suggestions",
      viewAll: "View all",
      remainingScans: "Remaining Scans",
      tipOfDay: "Nutrition of the Day",
      healthyTip: "Healthy Tip",
      anotherTip: "See another tip",
      tipMotto: "Better living starts on your plate",
    },
    scanner: {
      title: "Nutrition Scanner",
      instructions: "Point the camera at your plate or food",
      takePhoto: "Scan Plate",
      gallery: "Gallery",
      uploadPhoto: "Upload Photo",
      switchCamera: "Switch Camera",
      flash: "Flashlight",
      analyzing: "Analyzing Food...",
      calibratingHand: "Using biometric hand scale for exact portions",
      detectedFood: "Food detected!",
      foodStatusReady: "Plate in frame",
      foodStatusScanning: "Focusing...",
      foodStatusSearching: "Point at food",
      remainingScans: "Remaining scans",
      unlimited: "Unlimited",
      noScansLeft: "You have reached your free scan limit.",
      unlockMore: "Unlock More Scans",
      handCalibratedBadge: "Biometric Scale Active",
      handCalibratedDesc: "Place your hand beside your plate for precise measurements.",
      adjust: "Adjust",
      calibrateHandPrompt: "Want ultra-precise portions?",
      calibrateHandDesc: "Calibrate your hand once in your profile for high-accuracy meal sizing.",
      calibrate: "Calibrate",
      portion: "Portion",
      addMealSuccess: "Meal added to diary successfully!",
      confidence: "AI Confidence",
      cameraDisabled: "Camera Disabled",
      enableCamera: "Tap here to reactivate camera access",
      switchCameraTitle: "Switch front/rear camera",
    },
    shop: {
      title: "Shop & Premium Plans",
      subtitle: "Architecture of Nutri Intelligence",
      weekly: "Weekly",
      monthly: "Monthly",
      yearly: "Yearly",
      activePlan: "Active Plan",
      currentPlan: "Current Plan",
      subscribeNow: "Subscribe Now",
      upgradePlan: "Upgrade Plan",
      startTrial: "Start 7-Day Free Trial",
      trialButton: "Try 7 Days Free",
      trialActive: "Free Trial Active",
      freeTrialBadge: "7 Days Free",
      popularBadge: "Popular",
      bestValueBadge: "Best Value",
      cycleWeekly: "/week",
      cycleMonthly: "/month",
      cycleYearly: "/year",
      hintWeekly: "Great to get started",
      hintMonthly: "Most popular choice",
      hintYearly: "Save ~58%",
      whyPremium: "Why go Premium?",
      benefitsTitle: "Choose your journey",
      subStatus: "Subscription Status",
      statusActive: "Active",
      validUntil: "Valid until",
      cancelAnytime: "Auto-renewal · Cancel anytime",
      trialCancelAnytime: "7 days free · Cancel anytime",
      higherPlanActive: "Higher Plan Active",
      creditsPackTitle: "Scan Credit Packs (Consumable)",
      credits50Title: "50 Scans Pack",
      oneTimePayment: "/ one-time payment",
      credits50Desc:
        "Ideal if you have reached your period limit or prefer not to use a recurring subscription. Adds 50 permanent scans to your account.",
      buy50Scans: "Buy 50 Scans",
      why1Title: "Super AI Scans",
      why1Desc: "Ultra-detailed and instant identification",
      why2Title: "24/7 AI Nutritionist",
      why2Desc: "Ask questions and get healthy recipes anytime",
      why3Title: "Sentiment & Mood Analysis",
      why3Desc: "Understand how your diet affects energy and mood",
      why4Title: "Dynamic Goals",
      why4Desc: "Automatically adjust macros as you evolve",
      trialModalTitle: "Start 7 days free",
      trialModalSub: "Enjoy all benefits of the {plan} plan completely free for {days} days!",
      planPerksTitle: "Plan benefits:",
      totalToday: "Total Today",
      after7Days: "After 7 days",
      activateTrialBtn: "Activate Free Trial",
      maybeLater: "Maybe later",
      successTitle: "Plan Activated Successfully!",
      successTrialTitle: "Free Trial Activated!",
      successCreditsTitle: "50 Scans Added!",
      successDesc:
        "Congratulations! Your subscription is confirmed and access has been unlocked in real-time.",
      successTrialDesc: "You have 7 days of full access and scans to analyze all your meals.",
      successCreditsDesc: "50 scans have been credited to your account and are ready to use.",
      accountDetails: "YOUR ACCOUNT DETAILS:",
      totalScansAvailable: "total scans available",
      noExpiryCredits: "Credits with no expiration date",
      aiUnlocked: "AI detection and analysis unlocked",
      startScanningNow: "Start scanning now",
      openInApp: "Open in installed Android app",
      trialCancelNote: "Cancel anytime in your profile if you change your mind.",
      activePerksNote: "Your perks are already active on your account.",
      pWeekly1: "30 scans / week",
      pWeekly2: "AI Nutritionist Chat (50 messages)",
      pWeekly3: "Goal editing",
      pWeekly4: "Priority support",
      pMonthly1: "150 scans / month",
      pMonthly2: "AI Nutritionist Chat (50 messages / day)",
      pMonthly3: "Goal editing",
      pMonthly4: "Priority support",
      pMonthly5: "Extended history",
      pYearly1: "1200 scans / year",
      pYearly2: "AI Nutritionist Chat (150 messages / day)",
      pYearly3: "Goal editing",
      pYearly4: "Priority support",
      pYearly5: "Early access features",
    },
    profile: {
      title: "Profile",
      editProfile: "Edit Profile",
      adminPanel: "Admin Panel",
      subscriptions: "Subscriptions",
      rewards: "Rewards",
      history: "Scan History",
      goals: "Daily Targets",
      objective: "Objective",
      physicalData: "Physical Data",
      handCalibration: "Hand Calibration (High Precision)",
      changePassword: "Change Password",
      notifications: "Push Notifications",
      notificationsSub: "Enable alerts and daily reminders",
      privacy: "Rights & Privacy",
      deleteAccount: "Delete Account",
      signOut: "Sign Out",
      language: "App Language",
      sectionSubscription: "Subscription & History",
      sectionGoals: "Targets & Physical Data",
      sectionPreferences: "Preferences & Reminders",
      sectionSecurity: "Security & Account",
      languageSelectorTitle: "Select Language",
      chooseLanguage: "Choose your preferred language",
    },
    waterReminder: {
      title: "Hydration Reminders",
      tag: "WATER",
      subtitle: "Receive daily notifications to stay hydrated and boost your metabolism.",
      presetsTitle: "Time Presets",
      preset2h: "Every 2 hours",
      preset3h: "Every 3 hours",
      clearAll: "Clear all",
      scheduledTimes: "Your Scheduled Times",
      emptySchedule: "No times scheduled. Add one below!",
      addTime: "Add Time",
      timeInput: "Time",
      addButton: "Add",
      testButton: "Test Notifications",
      testingNotification: "Triggering test...",
      testSuccessToast: "Test triggered! Check your phone notifications.",
      maxTimesReached: "Maximum limit of 10 times reached.",
      timeAlreadyAdded: "This time has already been added.",
      timeAddedToast: "Time added successfully.",
      timeRemovedToast: "Time removed successfully.",
    },
    direitos: {
      title: "Rights & Privacy",
      termsTab: "Terms of Use",
      privacyTab: "Privacy Policy",
      copyLink: "Copy Link",
      copied: "Copied!",
      rightsTitle: "Terms of Use and General Conditions",
      privacyTitle: "Privacy Policy and Data Protection",
      backToProfile: "Back",
      lastUpdated: "Last updated: September 2026",
      terms: {
        introTitle: "1. Acceptance of Terms",
        introText:
          "By accessing and using the Sar scan application, you expressly agree to comply with all terms and conditions set forth herein. If you disagree with any provision, please discontinue using our services.",
        serviceTitle: "2. Description of Service",
        serviceText:
          "Sar scan is an artificial intelligence platform for food visual recognition, nutritional estimation, water tracking, and calorie/macronutrient management.",
        disclaimerTitle: "3. Medical Disclaimer",
        disclaimerText:
          "The Sar scan application is not a substitute for professional medical or nutritional diagnosis, prescription, or treatment. All information provided is strictly for informational and educational purposes.",
        accountTitle: "4. Account Registration and Security",
        accountText:
          "You are solely responsible for maintaining the confidentiality of your login credentials and for all activities under your account. Notify our team immediately if you suspect unauthorized access.",
        ipTitle: "5. Intellectual Property",
        ipText:
          "All algorithms, computer vision models, trademarks, logos, graphical interfaces, and software components in Sar scan are the exclusive property of its creators and protected by international copyright laws.",
      },
      privacy: {
        introTitle: "1. Data Collection and Usage",
        introText:
          "We collect data voluntarily provided by you (such as email, age, weight, height, nutritional goals, and food photos) solely to provide and enhance our AI features.",
        processingTitle: "2. Computer Vision and Biometrics",
        processingText:
          "Photos uploaded for food scanning and biometric hand calibration are processed through secure vision algorithms strictly to estimate portion sizes and nutrients.",
        storageTitle: "3. Storage and Encryption",
        storageText:
          "Your personal data is encrypted in transit and at rest using industry-standard protocols (AES-256 and SSL/TLS) and secured against unauthorized access.",
        rightsTitle: "4. Your Privacy Rights (GDPR / CCPA)",
        rightsText:
          "You hold the absolute right to access, rectify, export, or permanently delete all your data and historical records at any time using the Delete Account feature in your profile.",
        contactTitle: "5. Data Protection Contact",
        contactText:
          "For questions or requests regarding your data and privacy, please contact our support team through the in-app support channel.",
      },
    },
    editProfile: {
      title: "Edit Profile",
      name: "Full name",
      email: "Email",
      save: "Save Changes",
      success: "Profile updated successfully",
      changePhoto: "Change Photo",
      uploading: "Uploading...",
    },
    subpages: {
      changePassword: {
        title: "Change Password",
        cardTitle: "Account Security",
        cardSub: "Use at least 6 characters",
        current: "Current password",
        new: "New password",
        confirm: "Confirm new password",
        button: "Update Password",
        success: "Password updated successfully!",
      },
      rewards: {
        title: "Bonus Rewards",
        subtitle: "Scans and credits gifted by the administrator",
        claim: "Claim Reward",
        claimed: "Claimed",
        empty: "No rewards available at this time.",
        scansReward: "Gift Bonus Scans",
      },
      subscriptions: {
        title: "Subscriptions",
        subtitle: "Manage your current plan and premium access",
        active: "Active Plan",
        upgrade: "Switch to Premium",
        manage: "Manage Subscription",
        activeUntil: "Active until",
      },
      goals: {
        title: "Daily Targets",
        subtitle: "Adjust your calorie and macronutrient targets",
        calories: "Daily Calories (kcal)",
        protein: "Protein (g)",
        carbs: "Carbs (g)",
        fats: "Fats (g)",
        save: "Save Targets",
        success: "Targets saved successfully!",
      },
      objective: {
        title: "Your Goal",
        subtitle: "Select your primary nutritional objective",
        lose: "Lose Weight",
        loseDesc: "Calorie deficit for body fat reduction",
        maintain: "Maintain Weight",
        maintainDesc: "Calorie balance to keep current weight and health",
        gain: "Build Muscle",
        gainDesc: "Calorie surplus focused on hypertrophy",
        save: "Save Goal",
        success: "Goal updated successfully!",
      },
      physicalData: {
        title: "Physical Data",
        subtitle: "Update weight, height, and age to recalculate targets",
        weight: "Weight (kg)",
        height: "Height (cm)",
        age: "Age (years)",
        save: "Save Data",
        success: "Physical data updated successfully!",
      },
      handCalibration: {
        title: "Biometric Hand Calibration",
        subtitle: "Optical reference measurement for precise portion estimation",
        introTitle: "How Hand Calibration Works",
        introDesc:
          "Hand calibration creates a custom optical ruler. When placing your hand beside your plate in photos, the AI compares food dimensions to your real measurements to calculate exact grams and calories.",
        startBtn: "Start Calibration",
        selectObjectTitle: "Choose Reference Object",
        selectObjectDesc:
          "Pick a standard reference object you have on hand to establish dimensions:",
        cardName: "Card (Credit / ID)",
        cardDesc: "Global standard size (8.56 x 5.39 cm)",
        coinName: "Coin (2 Euros / 1 Dollar)",
        coinDesc: "Standard diameter (~2.57 cm)",
        sheetName: "A4 Sheet",
        sheetDesc: "Standard printer paper (21.0 x 29.7 cm)",
        nextStep: "Proceed to Camera",
        cameraGuideTitle: "Position Hand and Object",
        cameraGuideText:
          "Place your open hand palm down with the reference object beside it on a flat, well-lit surface.",
        captureBtn: "Capture & Analyze",
        analyzingTitle: "Analyzing Biometrics with AI...",
        analyzingDesc: "Detecting hand contours, knuckles, and millimeter scale...",
        resultTitle: "Calibration Completed Successfully!",
        resultDesc: "Your custom biometric scale is now active for all meal scans.",
        handLength: "Hand Length",
        palmWidth: "Palm Width",
        fingerWidth: "Index Width",
        confidence: "Confidence Score",
        recalibrateBtn: "Recalibrate Hand",
        backToProfile: "Back to Profile",
        errorTitle: "Could not calibrate",
        retryBtn: "Try Again",
        tipsHeader: "Tips for optimal calibration:",
        tip1: "Keep the camera directly perpendicular without tilt.",
        tip2: "Ensure hand and reference object are fully inside the frame.",
        tip3: "Use a well-lit area without harsh shadows.",
      },
      deleteAccount: {
        title: "Delete Account",
        warning:
          "This action is permanent and irreversible. All your data and history will be deleted.",
        confirmButton: "Yes, Delete My Account",
        confirmPrompt: "Type 'DELETE' to confirm:",
      },
    },
    search: {
      title: "Search Food",
      subtitle: "Search the nutrition database or use intelligent AI search",
      placeholder: "Type a food or meal name...",
      aiSearch: "Analyze with AI",
      recent: "Recent Searches",
      popularFoods: "Popular Foods",
      noResults: "Nothing found. Try the AI search above.",
      searching: "Searching food...",
      addToDiary: "Add to Diary",
      portion: "Portion",
      loadMore: "Load more ({count} remaining)",
      backToCategories: "← Back to category list",
      foodsCount: "{total} foods • {filtered}",
      categories: {
        all: "All",
        frutas: "Fruits",
        carnes: "Meat & Poultry",
        peixes: "Fish & Seafood",
        ovos_laticinios: "Eggs & Dairy",
        paes_massas: "Bread & Pasta",
        saladas_legumes: "Salads & Veggies",
        lanches: "Snacks & Pizza",
        bebidas: "Drinks & Shakes",
        doces: "Sweets & Desserts",
      },
    },
    diario: {
      title: "Food Diary",
      subtitle: "Track your calories, nutrients, and daily totals",
      today: "Today",
      yesterday: "Yesterday",
      history: "Log History",
      emptyDay: "No food logged for this day.",
      totalDay: "Daily Total",
      consumed: "Consumed",
      goal: "Target",
      remaining: "Remaining",
      protein: "Protein",
      carbs: "Carbs",
      fats: "Fats",
      water: "Water",
      calories: "Calories",
      deleteConfirm: "Delete Entry",
      deletePrompt: "Are you sure you want to delete this food from your diary?",
      speakNutrients: "Listen to Nutrients",
      stopAudio: "Stop Audio",
      mealDetails: "Meal Details",
      portion: "Portion",
      savedAt: "Logged at",
    },
    chat: {
      title: "Sar AI",
      subtitle: "24/7 Personal Nutrition Expert",
      statusOnline: "Online • Nutrition Expert",
      dailyUsage: "Daily Usage",
      unlimited: "Unlimited",
      campaignActive: "Bonus access active! Free Sar AI expires on:",
      campaignBadge: "CAMPAIGN",
      exclusiveTitle: "Exclusive Sar AI",
      exclusiveDesc:
        "Get a nutrition expert available 24/7 to answer questions, calculate macros, analyze meals, and create tailored meal plans.",
      exclusivePlans: "Available in Weekly, Monthly, and Yearly plans",
      unlockPremium: "Activate Premium Access",
      helloUser: "Hello, {name}! 👋",
      welcomeIntro:
        "I am Sar AI, your personal nutrition advisor. How can I help with your meals and fitness goals today?",
      analyzing: "Sar AI is analyzing...",
      placeholder: "Ask Sar AI or send meal photo (PNG/JPEG)...",
      send: "Send",
      emptyTitle: "How can I help you today?",
      emptySubtitle:
        "Ask about meals, get healthy recipes, or evaluate your daily nutritional plan.",
      clearChatTitle: "Clear History?",
      clearChatDesc: "This action will delete all messages exchanged with Sar AI.",
      clearConfirmBtn: "Delete",
      clearChat: "Clear Chat",
      limitReachedTitle: "Daily Limit Reached",
      limitReachedDesc:
        "You used all {limit} daily messages for your current plan. The limit will reset tomorrow.",
      upgradeUnlimited: "Upgrade to Yearly (Unlimited)",
      understood: "Understood",
      planProposed: "Proposed Nutrition Plan",
      planGoal: "Goal:",
      planStrategy: "Diet/Strategy:",
      planAcceptedBadge: "✅ Plan Accepted & Applied to Profile",
      planRejectedBadge: "❌ Plan Rejected",
      acceptPlan: "Accept Plan",
      rejectPlan: "Decline",
      planAppliedToast: "Nutrition plan successfully applied to your profile!",
      planRejectedToast: "Nutrition plan declined.",
      preset1: "What can I eat for a light dinner?",
      preset2: "How many calories are in chicken and rice?",
      preset3: "Tips to hit my daily protein target",
      promptCalcMacrosTitle: "Calculate my macros",
      promptCalcMacrosText:
        "I would like to calculate the ideal macronutrients for my current fitness goal.",
      promptWorkoutTitle: "Pre & post-workout",
      promptWorkoutText: "What are the best meal choices before and after my training sessions?",
      promptLunchTitle: "High-protein lunch",
      promptLunchText:
        "Give me a healthy, delicious, and easy-to-prepare high-protein lunch recipe.",
      promptFatLossTitle: "Fat loss strategies",
      promptFatLossText:
        "What nutritional strategies do you recommend to lose body fat while maintaining lean muscle?",
      imageFormatError: "Please upload images in PNG or JPEG format only.",
      historyClearedSuccess: "Conversation history cleared successfully.",
    },
    calibration: {
      title: "Hand Calibration",
      subtitle: "High-precision biometric reference for exact meal portions",
      howItWorks: "How Hand Calibration Works",
      howItWorksDesc:
        "Your hand serves as a permanent visual ruler. By measuring your hand once with a standard reference object, Sar scan calibrates dish pixels to estimate portions and nutrients with millimeter accuracy.",
      step1Title: "Choose a reference object",
      step1Desc: "Bank card/ID, 2€/1R$ coin, bottle cap, or ruler.",
      step2Title: "Place hand and object side by side",
      step2Desc: "Rest your open palm flat on a table and take a photo straight from above.",
      step3Title: "Automatic AI Calibration",
      step3Desc:
        "Our computer vision detects knuckle landmarks, palm width, and millimeter dimensions.",
      startCalibration: "Start Calibration",
      selectObject: "Select Reference Object",
      selectObjectDesc: "Select the object you will place next to your hand in the photo:",
      tabAll: "All Objects",
      tabCards: "Cards & Rulers",
      tabCoins: "Coins & Small Objects",
      creditCard: "Bank Card / ID / Loyalty Card",
      creditCardDesc: "Any standard ISO plastic card (credit, debit, ID)",
      coin2eur: "2 Euros Coin (€2)",
      coin2eurDesc: "Standard 2 Euro coin common in Europe (25.75 mm)",
      coin1real: "1 Real Coin (R$ 1)",
      coin1realDesc: "Standard Brazilian bimetallic 1 Real coin (27.00 mm)",
      coin1eur: "1 Euro Coin (€1)",
      coin1eurDesc: "Standard 1 Euro coin (23.25 mm)",
      bottleCap: "Plastic Bottle Cap",
      bottleCapDesc: "Standard beverage or soda plastic cap (28.00 mm)",
      ruler: "Ruler or Measuring Tape",
      rulerDesc: "Ruler with visible centimeter scale (metric scale)",
      photoTip: "Photo tip:",
      photoTipDesc:
        "Place your open hand and object flat on the table, parallel to the camera lens.",
      openCamera: "Open Camera",
      orUpload: "Or upload photo from gallery",
      cameraGuide: "Frame open hand and reference object in the same shot",
      handGuide: "Open Hand",
      calculating: "Analyzing Hand Biometrics...",
      calculatingDesc: "Calculating exact palm, finger, and optical scale dimensions...",
      profileActive: "Biometric Scale Active",
      scaleCalibrated: "Hand Calibrated Successfully!",
      accuracy: "Optical Accuracy",
      handLength: "Hand Length",
      wristToMiddleFinger: "From wrist to tip of middle finger",
      palmWidth: "Palm Width",
      palmTransversal: "Transverse palm width",
      howToUseDaily: "How to use in daily scans",
      howToUseDailyDesc:
        "When taking a photo of your plate, place your hand beside the food. Sar scan will recognize your hand ({length} cm) and automatically fine-tune grams and calories with precision!",
      goToScanner: "Go to Scanner",
      recalibrate: "Recalibrate",
      takeNewPhoto: "Take New Photo",
      sendGallery: "Upload from Gallery",
      changeObject: "Change Object",
      errorTitle: "Incomplete Verification",
      analyzedPhoto: "Analyzed photo",
      analysisReason: "Analysis Reason",
      analysisReasonDesc:
        "Could not clearly identify both your hand and the reference object in the frame.",
      howToResolve: "How to resolve in next photo:",
      howToResolveDesc:
        "Ensure your open palm is flat beside the reference object on a flat, well-lit surface.",
    },
  },
  fr: {
    common: {
      appName: "Sar scan",
      loading: "Chargement...",
      save: "Enregistrer",
      cancel: "Annuler",
      confirm: "Confirmer",
      error: "Erreur",
      success: "Succès",
      back: "Retour",
      close: "Fermer",
      search: "Rechercher",
      delete: "Supprimer",
      edit: "Modifier",
      continue: "Continuer",
      finish: "Terminer",
      yes: "Oui",
      no: "Non",
      or: "ou",
      all: "Tous",
      optional: "Facultatif",
      required: "Requis",
      retry: "Réessayer",
      copy: "Copier",
      copied: "Copié !",
      active: "Actif",
      inactive: "Inactif",
      upgrade: "Mettre à niveau",
      details: "Détails",
      viewAll: "Voir tout",
      none: "Aucun",
      select: "Sélectionner",
      share: "Partager",
      day: "jour",
      week: "semaine",
      month: "mois",
      year: "an",
      kcal: "kcal",
      g: "g",
      ml: "ml",
      cm: "cm",
      kg: "kg",
      years: "ans",
    },
    nav: {
      scanner: "Scanner",
      search: "Recherche",
      shop: "Boutique",
      profile: "Profil",
      chat: "Sar IA",
      diary: "Journal",
    },
    auth: {
      loginTitle: "Nourrissez vos objectifs",
      loginSubtitle: "Connectez-vous pour continuer à gérer votre nutrition et votre santé.",
      tabLogin: "SE CONNECTER",
      tabSignup: "Créer un compte",
      email: "E-mail",
      emailPlaceholder: "Votre adresse e-mail",
      password: "Mot de passe",
      passwordPlaceholder: "Entrez votre mot de passe",
      forgotPassword: "Mot de passe oublié ?",
      forgotPasswordLink: "Oublié ?",
      loginButton: "Se connecter à l'application",
      noAccount: "Vous n'avez pas de compte ?",
      createAccount: "Créer un compte",
      haveAccount: "Vous avez déjà un compte ?",
      signIn: "Se connecter",
      signUpTitle: "Commencez votre parcours",
      signUpSubtitle: "Créez votre compte pour scanner vos repas et transformer vos habitudes.",
      name: "Nom complet",
      namePlaceholder: "Votre prénom et nom",
      confirmPassword: "Confirmer le mot de passe",
      confirmPasswordPlaceholder: "Répétez votre mot de passe",
      signupButton: "Créer mon compte",
      termsAgreement: "En vous connectant, vous acceptez nos",
      termsLink: "Conditions d'utilisation et Politique de confidentialité",
      resetPasswordTitle: "Récupérer l'accès",
      resetPasswordSubtitle:
        "Indiquez votre e-mail pour recevoir un lien de réinitialisation de mot de passe.",
      sendResetEmail: "Envoyer le lien de réinitialisation",
      backToLogin: "Retour à la connexion",
      newPassword: "Nouveau mot de passe",
      updatePassword: "Réinitialiser le mot de passe",
      welcomeBack: "Bon retour parmi nous !",
      accountCreated: "Compte créé avec succès !",
      passwordsDoNotMatch: "Les mots de passe ne correspondent pas.",
      passwordTooShort: "Le mot de passe doit comporter au moins 6 caractères.",
      acceptTermsRequired: "Vous devez accepter les conditions d'utilisation pour continuer.",
      logoutConfirmTitle: "Déconnexion",
      logoutConfirmDesc: "Êtes-vous sûr de vouloir vous déconnecter ?",
      logoutButton: "Oui, me déconnecter",
      logoutCancel: "Annuler",
    },
    onboarding: {
      title: "Faisons connaissance",
      subtitle: "Renseignez vos données pour calculer vos objectifs nutritionnels personnalisés.",
      measuresTitle: "Vos Mesures",
      age: "Âge",
      ageUnit: "ans",
      weight: "Poids",
      weightUnit: "kg",
      height: "Taille",
      heightUnit: "cm",
      objectiveTitle: "Choisissez votre Objectif",
      loseWeight: "Perdre du Poids",
      loseWeightDesc: "Déficit modéré (-500 kcal/jour)",
      maintainWeight: "Maintenir le Poids",
      maintainWeightDesc: "Équilibre et stabilisation",
      gainMuscle: "Prendre du Muscle",
      gainMuscleDesc: "Surplus et hypertrophie (+300 kcal/jour)",
      submitButton: "Calculer mes objectifs & Continuer",
      celebrationTitle: "Bravo, vous arrivez à temps ! 🎉",
      celebrationSub:
        "Félicitations ! Votre inscription a été effectuée pendant notre campagne de bienvenue. Nous avons activé des bonus exclusifs sur votre compte :",
      bonusScansTitle: "Scans Alimentaires Activés",
      bonusScansDescPrefix: "Vous avez reçu",
      bonusScansDescMid: "scans bonus en plus des 3 offerts. Vous commencez avec",
      bonusScansDescSuffix: "scans !",
      bonusChatTitle: "Accès Gratuit à Sar IA",
      bonusChatDescPrefix: "Nous avons débloqué Sar IA pour",
      bonusChatDescSuffix: "jours gratuits (jusqu'à 30 messages par jour) pour vous guider !",
      claimCelebration: "Profiter des Bonus & Définir mes Objectifs",
      fillAllFields: "Veuillez remplir tous les champs obligatoires.",
      validAge: "Veuillez entrer un âge valide.",
      validWeight: "Veuillez entrer un poids valide (kg).",
      validHeight: "Veuillez entrer une taille valide (cm).",
      goalsCalculated: "Objectifs calculés avec succès !",
      langSelect: "Langue",
    },
    home: {
      greeting: "Bonjour",
      dailyGoal: "Objectif du Jour",
      caloriesToday: "Kcal d'Aujourd'hui",
      caloriesEaten: "Consommées",
      caloriesBurned: "Dépensées",
      remaining: "Restantes",
      protein: "Protéines",
      carbs: "Glucides",
      fats: "Lipides",
      water: "Eau",
      recentMeals: "Repas Récents",
      quickScan: "Scanner une Assiette",
      quickSearch: "Chercher un Aliment",
      aiCoach: "Discuter avec Sar IA",
      streak: "jours consécutifs",
      waterGlass: "verre",
      waterGlasses: "verres",
      addWater: "Ajouter de l'Eau",
      todaySummary: "Résumé du Jour",
      noMealsToday: "Aucun repas enregistré aujourd'hui.",
      clickToScan: "Appuyez pour scanner votre assiette avec l'IA",
      suggestions: "Suggestions",
      viewAll: "Voir tout",
      remainingScans: "Scans Restants",
      tipOfDay: "Nutrition du Jour",
      healthyTip: "Conseil Santé",
      anotherTip: "Voir un autre conseil",
      tipMotto: "Mieux vivre commence dans l'assiette",
    },
    scanner: {
      title: "Scanner Nutritionnel",
      instructions: "Pointez la caméra vers votre plat ou aliment",
      takePhoto: "Scanner l'Assiette",
      gallery: "Galerie",
      uploadPhoto: "Importer une Photo",
      switchCamera: "Changer de Caméra",
      flash: "Lampe Torche",
      analyzing: "Analyse des Aliments...",
      calibratingHand: "Utilisation de l'échelle biométrique de la main pour des portions exactes",
      detectedFood: "Aliment détecté !",
      foodStatusReady: "Assiette cadrée",
      foodStatusScanning: "Mise au point...",
      foodStatusSearching: "Pointez vers l'aliment",
      remainingScans: "Scans restants",
      unlimited: "Illimité",
      noScansLeft: "Vous avez atteint la limite de scans gratuits.",
      unlockMore: "Débloquer Plus de Scans",
      handCalibratedBadge: "Échelle Biométrique Active",
      handCalibratedDesc: "Placez votre main à côté de l'assiette pour des portions exactes.",
      adjust: "Ajuster",
      calibrateHandPrompt: "Vous voulez des portions ultra-précises ?",
      calibrateHandDesc:
        "Calibrez votre main une fois dans votre profil pour des mesures chirurgicales.",
      calibrate: "Calibrer",
      portion: "Portion",
      addMealSuccess: "Repas ajouté au journal avec succès !",
      confidence: "Précision de l'IA",
      cameraDisabled: "Caméra Désactivée",
      enableCamera: "Appuyez ici pour réactiver l'accès caméra",
      switchCameraTitle: "Changer caméra avant/arrière",
    },
    shop: {
      title: "Boutique & Abonnements Premium",
      subtitle: "Architecture d'Intelligence Nutritionnelle",
      weekly: "Hebdomadaire",
      monthly: "Mensuel",
      yearly: "Annuel",
      activePlan: "Plan Actif",
      currentPlan: "Plan Actuel",
      subscribeNow: "S'abonner Maintenant",
      upgradePlan: "Changer de Forfait",
      startTrial: "Activer 7 Jours Gratuits",
      trialButton: "Essayer 7 Jours",
      trialActive: "Essai Gratuit Actif",
      freeTrialBadge: "7 Jours Gratuits",
      popularBadge: "Populaire",
      bestValueBadge: "Meilleure Offre",
      cycleWeekly: "/semaine",
      cycleMonthly: "/mois",
      cycleYearly: "/an",
      hintWeekly: "Idéal pour tester",
      hintMonthly: "Le plus plébiscité",
      hintYearly: "Économisez ~58%",
      whyPremium: "Pourquoi devenir Premium ?",
      benefitsTitle: "Choisissez votre formule",
      subStatus: "Statut de l'Abonnement",
      statusActive: "Actif",
      validUntil: "Valable jusqu'au",
      cancelAnytime: "Renouvellement automatique · Résiliation sans frais",
      trialCancelAnytime: "7 jours gratuits · Résiliation sans frais",
      higherPlanActive: "Forfait Supérieur Déjà Actif",
      creditsPackTitle: "Packs de Scans (Consommables)",
      credits50Title: "Pack de 50 Scans",
      oneTimePayment: "/ paiement unique",
      credits50Desc:
        "Idéal si vous avez atteint votre limite périodique ou préférez ne pas souscrire d'abonnement récurrent. Ajoute 50 scans définitifs à votre compte.",
      buy50Scans: "Acheter 50 Scans",
      why1Title: "Scans avec Super IA",
      why1Desc: "Identification instantanée et ultra-détaillée",
      why2Title: "Nutritionniste IA 24/7",
      why2Desc: "Posez vos questions et obtenez des recettes sur mesure",
      why3Title: "Analyse de Sentiment & Humeur",
      why3Desc: "Comprenez l'impact de vos repas sur votre forme",
      why4Title: "Objectifs Dynamiques",
      why4Desc: "Ajustez vos macronutriments au fil de votre progression",
      trialModalTitle: "Profitez de 7 jours gratuits",
      trialModalSub:
        "Testez tous les avantages du forfait {plan} 100% gratuitement pendant {days} jours !",
      planPerksTitle: "Avantages inclus :",
      totalToday: "Total Aujourd'hui",
      after7Days: "Après 7 jours",
      activateTrialBtn: "Activer l'Essai Gratuit",
      maybeLater: "Peut-être plus tard",
      successTitle: "Abonnement Activé avec Succès !",
      successTrialTitle: "Essai Gratuit Activé !",
      successCreditsTitle: "50 Scans Ajoutés !",
      successDesc: "Félicitations ! Votre accès a été débloqué en temps réel.",
      successTrialDesc: "Vous disposez de 7 jours d'accès complet pour scanner vos plats.",
      successCreditsDesc: "50 scans ont été crédités sur votre compte et sont prêts à l'emploi.",
      accountDetails: "DÉTAILS DE VOTRE COMPTE :",
      totalScansAvailable: "scans au total disponibles",
      noExpiryCredits: "Crédits sans date d'expiration",
      aiUnlocked: "Détection et analyse par IA débloquées",
      startScanningNow: "Commencer à scanner",
      openInApp: "Ouvrir dans l'application Android",
      trialCancelNote: "Résiliable à tout moment depuis votre profil.",
      activePerksNote: "Vos privilèges sont déjà appliqués à votre compte.",
      pWeekly1: "30 scans / semaine",
      pWeekly2: "Chat Nutritionniste IA (50 messages)",
      pWeekly3: "Édition des objectifs",
      pWeekly4: "Support prioritaire",
      pMonthly1: "150 scans / mois",
      pMonthly2: "Chat Nutritionniste IA (50 messages / jour)",
      pMonthly3: "Édition des objectifs",
      pMonthly4: "Support prioritaire",
      pMonthly5: "Historique étendu",
      pYearly1: "1200 scans / an",
      pYearly2: "Chat Nutritionniste IA (150 messages / jour)",
      pYearly3: "Édition des objectifs",
      pYearly4: "Support prioritaire",
      pYearly5: "Accès anticipé aux nouveautés",
    },
    profile: {
      title: "Profil",
      editProfile: "Modifier le Profil",
      adminPanel: "Panneau d'Administration",
      subscriptions: "Abonnements",
      rewards: "Récompenses",
      history: "Historique de Scans",
      goals: "Objectifs Quotidiens",
      objective: "Objectif",
      physicalData: "Données Physiques",
      handCalibration: "Calibration de la Main (Haute Précision)",
      changePassword: "Changer de Mot de Passe",
      notifications: "Notifications Push",
      notificationsSub: "Activer les rappels quotidiens",
      privacy: "Droits & Confidentialité",
      deleteAccount: "Supprimer le Compte",
      signOut: "Se Déconnecter",
      language: "Langue de l'Application",
      sectionSubscription: "Abonnement & Historique",
      sectionGoals: "Objectifs & Données Physiques",
      sectionPreferences: "Préférences & Rappels",
      sectionSecurity: "Sécurité & Compte",
      languageSelectorTitle: "Sélectionner la Langue",
      chooseLanguage: "Choisissez votre langue préférée",
    },
    waterReminder: {
      title: "Rappels d'Hydratation",
      tag: "EAU",
      subtitle:
        "Recevez des notifications quotidiennes pour rester hydraté et stimuler votre métabolisme.",
      presetsTitle: "Intervalles Prédéfinis",
      preset2h: "Toutes les 2 heures",
      preset3h: "Toutes les 3 heures",
      clearAll: "Tout effacer",
      scheduledTimes: "Vos Horaires Programmés",
      emptySchedule: "Aucun horaire programmé. Ajoutez-en un ci-dessous !",
      addTime: "Ajouter un Horaire",
      timeInput: "Heure",
      addButton: "Ajouter",
      testButton: "Tester les Notifications",
      testingNotification: "Envoi du test...",
      testSuccessToast: "Test déclenché ! Vérifiez les notifications de votre téléphone.",
      maxTimesReached: "Limite maximale de 10 horaires atteinte.",
      timeAlreadyAdded: "Cet horaire a déjà été ajouté.",
      timeAddedToast: "Horaire ajouté avec succès.",
      timeRemovedToast: "Horaire supprimé avec succès.",
    },
    direitos: {
      title: "Droits & Confidentialité",
      termsTab: "Conditions d'Utilisation",
      privacyTab: "Politique de Confidentialité",
      copyLink: "Copier le Lien",
      copied: "Copié !",
      rightsTitle: "Conditions Générales d'Utilisation",
      privacyTitle: "Politique de Confidentialité et Protection des Données",
      backToProfile: "Retour",
      lastUpdated: "Dernière mise à jour : Septembre 2026",
      terms: {
        introTitle: "1. Acceptation des Conditions",
        introText:
          "En accédant et en utilisant l'application Sar scan, vous acceptez expressément de respecter l'ensemble des présentes conditions générales. Si vous n'êtes pas d'accord, veuillez cesser l'utilisation de nos services.",
        serviceTitle: "2. Description du Service",
        serviceText:
          "Sar scan est une plateforme d'intelligence artificielle dédiée à la reconnaissance visuelle des aliments, au calcul nutritionnel et au suivi des calories, macronutriments et hydratation.",
        disclaimerTitle: "3. Avertissement Médical",
        disclaimerText:
          "L'application Sar scan ne constitue en aucun cas un substitut à un diagnostic médical ou diététique professionnel. Toutes les données sont fournies à titre informatif et indicatif.",
        accountTitle: "4. Sécurité et Gestion du Compte",
        accountText:
          "Vous êtes seul responsable de la confidentialité de vos identifiants. Prévenez immédiatement notre équipe en cas d'utilisation suspecte ou non autorisée de votre compte.",
        ipTitle: "5. Propriété Intellectuelle",
        ipText:
          "L'ensemble des algorithmes de vision par ordinateur, logos, chartes graphiques et technologies utilisés au sein de Sar scan sont protégés par les lois internationales sur la propriété intellectuelle.",
      },
      privacy: {
        introTitle: "1. Collecte et Utilisation des Données",
        introText:
          "Nous collectons uniquement les informations fournies volontairement (e-mail, mensurations, objectifs et photos d'aliments) afin d'assurer et perfectionner l'analyse nutritionnelle IA.",
        processingTitle: "2. Traitement Visuel et Biométrie",
        processingText:
          "Les images transmises pour l'analyse des repas et la calibration biométrique de la main sont traitées par nos modèles de vision sécurisés uniquement pour l'évaluation des portions.",
        storageTitle: "3. Sécurité et Chiffrement",
        storageText:
          "Vos données personnelles sont stockées sur des serveurs sécurisés et bénéficient d'un chiffrement robuste de bout en bout (AES-256 et protocoles TLS).",
        rightsTitle: "4. Vos Droits (RGPD)",
        rightsText:
          "Vous disposez d'un droit absolu d'accès, de rectification, de portabilité et de suppression intégrale de vos données à tout moment via l'option Supprimer le Compte dans votre profil.",
        contactTitle: "5. Contact & Délégué à la Protection",
        contactText:
          "Pour toute demande relative à vos données personnelles, vous pouvez contacter directement notre équipe via le support intégré à l'application.",
      },
    },
    editProfile: {
      title: "Modifier le Profil",
      name: "Nom complet",
      email: "E-mail",
      save: "Enregistrer les modifications",
      success: "Profil mis à jour avec succès",
      changePhoto: "Changer de photo",
      uploading: "Téléversement...",
    },
    subpages: {
      changePassword: {
        title: "Changer de Mot de Passe",
        cardTitle: "Sécurité du compte",
        cardSub: "Utilisez au moins 6 caractères",
        current: "Mot de passe actuel",
        new: "Nouveau mot de passe",
        confirm: "Confirmer le mot de passe",
        button: "Mettre à jour le mot de passe",
        success: "Mot de passe mis à jour avec succès !",
      },
      rewards: {
        title: "Récompenses Bonus",
        subtitle: "Scans et crédits offerts par l'administrateur",
        claim: "Récupérer la récompense",
        claimed: "Récupéré",
        empty: "Aucune récompense disponible pour le moment.",
        scansReward: "Scans Bonus Cadeau",
      },
      subscriptions: {
        title: "Abonnements",
        subtitle: "Gérez votre formule actuelle et vos avantages premium",
        active: "Formule Active",
        upgrade: "Passer à Premium",
        manage: "Gérer l'Abonnement",
        activeUntil: "Actif jusqu'au",
      },
      goals: {
        title: "Objectifs Quotidiens",
        subtitle: "Ajustez vos cibles en calories et macronutriments",
        calories: "Calories quotidiennes (kcal)",
        protein: "Protéines (g)",
        carbs: "Glucides (g)",
        fats: "Lipides (g)",
        save: "Enregistrer les Objectifs",
        success: "Objectifs enregistrés avec succès !",
      },
      objective: {
        title: "Votre Objectif",
        subtitle: "Sélectionnez votre orientation nutritionnelle",
        lose: "Perdre du Poids",
        loseDesc: "Déficit calorique pour brûler les graisses",
        maintain: "Maintenir le Poids",
        maintainDesc: "Équilibre calorique pour stabiliser la forme",
        gain: "Prendre de la Masse",
        gainDesc: "Surplus calorique axé sur l'hypertrophie",
        save: "Enregistrer l'Objectif",
        success: "Objectif mis à jour avec succès !",
      },
      physicalData: {
        title: "Données Physiques",
        subtitle: "Mettez à jour poids, taille et âge pour recalculer vos cibles",
        weight: "Poids (kg)",
        height: "Taille (cm)",
        age: "Âge (ans)",
        save: "Enregistrer les Données",
        success: "Données physiques mises à jour !",
      },
      handCalibration: {
        title: "Calibration Biométrique de la Main",
        subtitle: "Mesure de référence optique pour une précision maximale des portions",
        introTitle: "Fonctionnement de la Calibration",
        introDesc:
          "La calibration crée une référence optique personnalisée. En posant votre main à côté de l'assiette lors des photos, l'IA compare les dimensions réelles pour calculer le grammage exact.",
        startBtn: "Commencer la Calibration",
        selectObjectTitle: "Choisissez un Objet de Référence",
        selectObjectDesc:
          "Sélectionnez un objet standard à portée de main pour étalonner l'échelle :",
        cardName: "Carte (Bancaire / Identité)",
        cardDesc: "Format standard international (8,56 x 5,39 cm)",
        coinName: "Pièce (2 Euros / 1 Dollar)",
        coinDesc: "Diamètre standard (~2,57 cm)",
        sheetName: "Feuille A4",
        sheetDesc: "Papier standard (21,0 x 29,7 cm)",
        nextStep: "Passer à la Caméra",
        cameraGuideTitle: "Positionnez la Main et l'Objet",
        cameraGuideText:
          "Posez votre main à plat et l'objet de référence côte à côte sur une surface bien éclairée.",
        captureBtn: "Capturer et Analyser",
        analyzingTitle: "Analyse Biométrique par IA...",
        analyzingDesc: "Détection des contours, articulations et échelle millimétrique...",
        resultTitle: "Calibration Réussie avec Succès !",
        resultDesc: "Votre échelle biométrique est active pour tous vos scans d'assiettes.",
        handLength: "Longueur de la Main",
        palmWidth: "Largeur de la Paume",
        fingerWidth: "Largeur de l'Index",
        confidence: "Indice de Confiance",
        recalibrateBtn: "Recalibrer la Main",
        backToProfile: "Retour au Profil",
        errorTitle: "Calibration impossible",
        retryBtn: "Réessayer",
        tipsHeader: "Conseils pour une calibration réussie :",
        tip1: "Tenez la caméra bien droite et perpendiculaire.",
        tip2: "Assurez-vous que la main et l'objet sont entièrement visibles.",
        tip3: "Privilégiez un environnement bien éclairé sans ombres prononcées.",
      },
      deleteAccount: {
        title: "Supprimer le Compte",
        warning:
          "Cette action est irréversible. Toutes vos données et historiques seront définitivement effacés.",
        confirmButton: "Oui, Supprimer Mon Compte",
        confirmPrompt: "Tapez 'SUPPRIMER' pour confirmer :",
      },
    },
    search: {
      title: "Recherche d'Aliments",
      subtitle: "Consultez la base nutritionnelle ou utilisez la recherche intelligente par IA",
      placeholder: "Nom de l'aliment ou du plat...",
      aiSearch: "Analyser avec l'IA",
      recent: "Recherches Récentes",
      popularFoods: "Aliments Populaires",
      noResults: "Aucun résultat trouvé. Utilisez la recherche IA ci-dessus.",
      searching: "Recherche en cours...",
      addToDiary: "Ajouter au Journal",
      portion: "Portion",
      loadMore: "Charger plus ({count} restants)",
      backToCategories: "← Retour à la liste des catégories",
      foodsCount: "{total} aliments • {filtered}",
      categories: {
        all: "Tous",
        frutas: "Fruits",
        carnes: "Viandes & Volailles",
        peixes: "Poissons & Fruits de Mer",
        ovos_laticinios: "Œufs & Produits Laitiers",
        paes_massas: "Pains & Féculents",
        saladas_legumes: "Salades & Légumes",
        lanches: "Snacks & Pizzas",
        bebidas: "Boissons & Shakes",
        doces: "Douceurs & Desserts",
      },
    },
    diario: {
      title: "Journal Alimentaire",
      subtitle: "Suivez vos calories, macronutriments et totaux quotidiens",
      today: "Aujourd'hui",
      yesterday: "Hier",
      history: "Historique des Repas",
      emptyDay: "Aucun repas enregistré pour ce jour.",
      totalDay: "Total du Jour",
      consumed: "Consommé",
      goal: "Objectif",
      remaining: "Restant",
      protein: "Protéines",
      carbs: "Glucides",
      fats: "Lipides",
      water: "Eau",
      calories: "Calories",
      deleteConfirm: "Supprimer l'Entrée",
      deletePrompt: "Voulez-vous vraiment supprimer cet aliment de votre journal ?",
      speakNutrients: "Écouter les Nutriments",
      stopAudio: "Arrêter l'Audio",
      mealDetails: "Détails du Repas",
      portion: "Portion",
      savedAt: "Enregistré à",
    },
    chat: {
      title: "Sar IA",
      subtitle: "Expert Nutritionniste Personnel 24/7",
      statusOnline: "En ligne • Expert en Nutrition",
      dailyUsage: "Usage Quotidien",
      unlimited: "Illimité",
      campaignActive: "Accès bonus actif ! Sar IA gratuit expire le :",
      campaignBadge: "CAMPAGNE",
      exclusiveTitle: "Sar IA Exclusif",
      exclusiveDesc:
        "Bénéficiez d'un expert en nutrition disponible 24h/24 pour répondre à vos questions, calculer vos macros, analyser vos assiettes et élaborer des régimes personnalisés.",
      exclusivePlans: "Disponible dans les forfaits Hebdomadaire, Mensuel et Annuel",
      unlockPremium: "Activer l'Accès Premium",
      helloUser: "Bonjour, {name} ! 👋",
      welcomeIntro:
        "Je suis Sar IA, votre assistant expert en nutrition. Comment puis-je vous aider avec votre alimentation et vos objectifs aujourd'hui ?",
      analyzing: "Sar IA analyse...",
      placeholder: "Posez une question à Sar IA ou envoyez une photo (PNG/JPEG)...",
      send: "Envoyer",
      emptyTitle: "Comment puis-je vous aider aujourd'hui ?",
      emptySubtitle:
        "Posez vos questions sur votre alimentation, demandez des recettes saines ou évaluez vos repas.",
      clearChatTitle: "Effacer l'historique ?",
      clearChatDesc: "Cette action supprimera tous les messages échangés avec Sar IA.",
      clearConfirmBtn: "Supprimer",
      clearChat: "Effacer la Conversation",
      limitReachedTitle: "Limite Quotidienne Atteinte",
      limitReachedDesc:
        "Vous avez utilisé tous vos {limit} messages quotidiens pour votre forfait. La limite sera réinitialisée demain.",
      upgradeUnlimited: "Passer à l'Annuel (Illimité)",
      understood: "Compris",
      planProposed: "Plan Nutritionnel Proposé",
      planGoal: "Objectif :",
      planStrategy: "Régime/Stratégie :",
      planAcceptedBadge: "✅ Plan Accepté & Appliqué au Profil",
      planRejectedBadge: "❌ Plan Refusé",
      acceptPlan: "Accepter le Plan",
      rejectPlan: "Refuser",
      planAppliedToast: "Plan nutritionnel appliqué avec succès à votre profil !",
      planRejectedToast: "Plan nutritionnel refusé.",
      preset1: "Que manger pour un dîner léger ?",
      preset2: "Combien de calories dans du poulet et du riz ?",
      preset3: "Conseils pour atteindre mon quota de protéines",
      promptCalcMacrosTitle: "Calculer mes macros",
      promptCalcMacrosText:
        "J'aimerais calculer mes macronutriments idéaux pour mon objectif actuel.",
      promptWorkoutTitle: "Pré & post-entraînement",
      promptWorkoutText:
        "Quelles sont les meilleures options de repas avant et après mon entraînement ?",
      promptLunchTitle: "Déjeuner protéiné",
      promptLunchText:
        "Donne-moi une suggestion de déjeuner sain, riche en protéines et facile à préparer.",
      promptFatLossTitle: "Conseils pour sécher",
      promptFatLossText:
        "Quelles stratégies nutritionnelles recommandes-tu pour brûler des graisses tout en gardant du muscle ?",
      imageFormatError: "Veuillez envoyer uniquement des images aux formats PNG ou JPEG.",
      historyClearedSuccess: "Historique de conversation effacé avec succès.",
    },
    calibration: {
      title: "Calibration de la Main",
      subtitle: "Mesure biométrique de haute précision pour des portions exactes",
      howItWorks: "Comment fonctionne la calibration",
      howItWorksDesc:
        "Votre main sert de règle visuelle permanente. En enregistrant vos mesures réelles avec un objet de référence, Sar scan calibre les pixels de chaque plat pour estimer portions et nutriments avec une précision chirurgicale.",
      step1Title: "Choisissez un objet de référence",
      step1Desc: "Carte bancaire/ID, pièce de 2€/1R$, bouchon ou règle.",
      step2Title: "Placez la main et l'objet côte à côte",
      step2Desc: "Posez la paume ouverte sur une table lisse et prenez une photo bien du dessus.",
      step3Title: "Calibration Automatique par IA",
      step3Desc:
        "Notre algorithme détecte les articulations, la paume et la taille en millimètres.",
      startCalibration: "Démarrer la Calibration",
      selectObject: "Sélectionnez l'Objet de Référence",
      selectObjectDesc:
        "Sélectionnez l'objet que vous placerez à côté de votre main sur la photo :",
      tabAll: "Tous les Objets",
      tabCards: "Cartes & Règles",
      tabCoins: "Pièces & Petits Objets",
      creditCard: "Carte Bancaire / ID / Fidélité",
      creditCardDesc: "Toute carte plastique standard ISO (crédit, débit, ID)",
      coin2eur: "Pièce de 2 Euros (€2)",
      coin2eurDesc: "Pièce standard de 2 Euros courante en Europe (25,75 mm)",
      coin1real: "Pièce de 1 Real (R$ 1)",
      coin1realDesc: "Pièce bimétallique standard brésilienne de 1 Real (27,00 mm)",
      coin1eur: "Pièce de 1 Euro (€1)",
      coin1eurDesc: "Pièce standard de 1 Euro (23,25 mm)",
      bottleCap: "Bouchon de Bouteille",
      bottleCapDesc: "Bouchon en plastique standard d'eau ou soda (28,00 mm)",
      ruler: "Règle ou Mètre Ruban",
      rulerDesc: "Règle avec repères visibles en centimètres (échelle métrique)",
      photoTip: "Astuce photo :",
      photoTipDesc: "Posez la main ouverte et l'objet bien à plat sur la table, face à l'objectif.",
      openCamera: "Ouvrir la Caméra",
      orUpload: "Ou importer depuis la galerie",
      cameraGuide: "Cadrez la main ouverte et l'objet de référence sur la même photo",
      handGuide: "Main Ouverte",
      calculating: "Analyse de la Biométrie...",
      calculatingDesc: "Calcul des dimensions exactes de la paume, des doigts et de l'échelle...",
      profileActive: "Échelle Biométrique Active",
      scaleCalibrated: "Main Calibrée avec Succès !",
      accuracy: "Précision Optique",
      handLength: "Longueur de la Main",
      wristToMiddleFinger: "Du poignet à l'extrémité du majeur",
      palmWidth: "Largeur de la Paume",
      palmTransversal: "Largeur transversale de la paume",
      howToUseDaily: "Comment l'utiliser au quotidien",
      howToUseDailyDesc:
        "Lors de la photo de votre repas, placez votre main à côté de l'assiette. Sar scan reconnaîtra votre main ({length} cm) et ajustera les grammes et calories avec précision !",
      goToScanner: "Aller au Scanner",
      recalibrate: "Recalibrer",
      takeNewPhoto: "Prendre une Nouvelle Photo",
      sendGallery: "Importer de la Galerie",
      changeObject: "Changer d'Objet",
      errorTitle: "Vérification Incomplète",
      analyzedPhoto: "Photo analysée",
      analysisReason: "Raison de l'Analyse",
      analysisReasonDesc:
        "Impossible d'identifier nettement la main et l'objet de référence sur la même image.",
      howToResolve: "Comment résoudre sur la prochaine photo :",
      howToResolveDesc:
        "Veillez à bien poser la main ouverte à côté de l'objet sur une table bien éclairée sans ombre portée.",
    },
  },
};

export function getCurrentLanguage(): Language {
  if (typeof window === "undefined") return "pt";
  const saved = localStorage.getItem("app_language") as Language;
  if (saved && (saved === "pt" || saved === "en" || saved === "fr")) {
    return saved;
  }
  const browserLang = navigator.language.slice(0, 2).toLowerCase();
  if (browserLang === "en") return "en";
  if (browserLang === "fr") return "fr";
  return "pt";
}

export function setAppLanguage(lang: Language) {
  if (typeof window === "undefined") return;
  localStorage.setItem("app_language", lang);
  window.dispatchEvent(new Event("languagechange"));
}

export function useTranslation() {
  const [lang, setLang] = useState<Language>(getCurrentLanguage);

  useEffect(() => {
    const handleLangChange = () => {
      setLang(getCurrentLanguage());
    };
    window.addEventListener("languagechange", handleLangChange);
    window.addEventListener("storage", handleLangChange);
    return () => {
      window.removeEventListener("languagechange", handleLangChange);
      window.removeEventListener("storage", handleLangChange);
    };
  }, []);

  const t = (path: string, params?: Record<string, string | number>): string => {
    const keys = path.split(".");
    let current: any = translations[lang] || translations.pt;
    for (const key of keys) {
      if (current && typeof current === "object" && key in current) {
        current = current[key];
      } else {
        // Fallback to Portuguese if key not found in chosen language
        let fallback: any = translations.pt;
        for (const fbKey of keys) {
          if (fallback && typeof fallback === "object" && fbKey in fallback) {
            fallback = fallback[fbKey];
          } else {
            return path;
          }
        }
        current = fallback;
        break;
      }
    }

    if (typeof current === "string") {
      let result = current;
      if (params) {
        Object.entries(params).forEach(([k, v]) => {
          result = result.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
        });
      }
      return result;
    }
    return path;
  };

  return {
    t,
    lang,
    setLanguage: setAppLanguage,
    translateFoodName: (name: string) => translateFoodName(name, lang),
  };
}
