import { useState, useEffect } from "react";

export const translations = {
  pt: {
    common: {
      appName: "NutriScan AI",
      loading: "Carregando...",
      save: "Salvar",
      cancel: "Cancelar",
      confirm: "Confirmar",
      error: "Erro",
      success: "Sucesso",
      back: "Voltar",
      close: "Fechar",
    },
    nav: {
      scanner: "Scanner",
      search: "Buscar",
      shop: "Loja",
      profile: "Perfil",
      chat: "Nutricionista",
    },
    auth: {
      loginTitle: "Entrar na sua conta",
      emailPlaceholder: "seu@email.com",
      passwordPlaceholder: "Sua senha",
      loginButton: "Entrar",
    },
    home: {
      greeting: "Olá",
      dailyGoal: "Meta Diária",
      caloriesEaten: "Consumidas",
      caloriesBurned: "Gasto",
      remaining: "Restantes",
      protein: "Proteínas",
      carbs: "Carboidratos",
      fats: "Gorduras",
      water: "Água",
      recentMeals: "Refeições Recentes",
      quickScan: "Escanear Prato",
      quickSearch: "Buscar Alimento",
      aiCoach: "Conversar com Nutricionista IA",
    },
    shop: {
      title: "Loja & Planos Premium",
      subtitle: "Desbloqueie todo o poder da inteligência artificial nutricional",
      weekly: "Plano Semanal",
      monthly: "Plano Mensal",
      yearly: "Plano Anual",
      activePlan: "Plano Atual",
      subscribeNow: "Assinar Agora",
      featuresTitle: "Vantagens Exclusivas",
      f1: "Scans nutricionais ilimitados por IA",
      f2: "Calibração biométrica da mão de alta precisão",
      f3: "Chat ilimitado com Nutricionista IA 24/7",
      f4: "Relatórios avançados e gráficos detalhados",
      cycleWeekly: "/semana",
      cycleMonthly: "/mês",
      cycleYearly: "/ano",
      hintWeekly: "Ideal para experimentar",
      hintMonthly: "Mais escolhido",
      hintYearly: "Economize ~58%",
      badgePopular: "Popular",
      badgeBestValue: "Melhor valor",
      creditsTitle: "Pacote Extra de Scans",
      creditsSub: "Precisa de mais scans sem assinar? Adquira créditos instantâneos.",
      buyCredits: "Comprar 50 Scans",
      mySubscription: "Sua Assinatura Premium",
      activeStatus: "Ativa",
      cancelSub: "Cancelar Assinatura",
      restorePurchases: "Restaurar Compras",
      faqTitle: "Dúvidas Frequentes",
    },
    profile: {
      title: "Perfil",
      editProfile: "Editar Perfil",
      adminPanel: "Painel de Administração",
      subscriptions: "Assinaturas",
      rewards: "Recompensas",
      history: "Histórico de Leitura",
      goals: "Metas Diárias",
      objective: "Objetivo",
      physicalData: "Dados Físicos",
      handCalibration: "Calibração da Mão (Alta Precisión)",
      changePassword: "Alterar Senha",
      notifications: "Notificações Push",
      notificationsSub: "Ativar alertas e lembretes diários",
      privacy: "Direitos e Privacidade",
      deleteAccount: "Excluir Conta",
      signOut: "Sair da Conta",
      language: "Idioma do Aplicativo",
      sectionSubscription: "Assinatura & Histórico",
      sectionGoals: "Metas & Dados Físicos",
      sectionPreferences: "Preferências & Lembretes",
      sectionSecurity: "Segurança & Conta",
    },
    waterReminder: {
      title: "Lembretes de Hidratação",
      subtitle: "Notificações diárias para beber água e acelerar metabolismo",
      active: "Ativar Lembretes",
      addTime: "Adicionar Horário",
      savedTimes: "Horários Agendados",
      notificationTitle: "Hora de beber água! 💧",
      notificationBody: "Mantenha o seu corpo hidratado para acelerar o seu metabolismo.",
    },
    direitos: {
      title: "Direitos e Privacidade",
      termsTab: "Termos de Uso",
      privacyTab: "Política de Privacidade",
      copyLink: "Copiar Link",
      copied: "Copiado!",
      rightsTitle: "Termos de Uso e Condições Gerais",
      privacyTitle: "Política de Privacidade e Proteção de Dados",
    },
    editProfile: {
      title: "Editar Perfil",
      name: "Nome completo",
      email: "E-mail",
      save: "Salvar Alterações",
      success: "Perfil atualizado com sucesso",
    },
    subpages: {
      changePassword: {
        title: "Alterar Senha",
        cardTitle: "Segurança da conta",
        cardSub: "Use ao menos 6 caracteres",
        current: "Senha atual",
        new: "Nova senha",
        confirm: "Confirmar nova senha",
        button: "Atualizar Senha",
      },
      rewards: {
        title: "Recompensas Bônus",
        subtitle: "Scans e créditos enviados pelo administrador",
        claim: "Resgatar Recompensa",
        claimed: "Resgatado",
        empty: "Nenhuma recompensa disponível no momento.",
      },
      subscriptions: {
        title: "Assinaturas",
        subtitle: "Gerencie seu plano atual e acesso premium",
        active: "Plano Ativo",
        upgrade: "Mudar para Premium",
      },
      goals: {
        title: "Metas Diárias",
        calories: "Calorias Diárias (kcal)",
        protein: "Proteínas (g)",
        carbs: "Carboidratos (g)",
        fats: "Gorduras (g)",
        save: "Salvar Metas",
      },
      objective: {
        title: "Seu Objetivo",
        lose: "Perder Peso",
        maintain: "Manter Peso",
        gain: "Ganhar Massa Muscular",
      },
      physicalData: {
        title: "Dados Físicos",
        weight: "Peso (kg)",
        height: "Altura (cm)",
        age: "Idade (anos)",
        save: "Salvar Dados",
      },
      handCalibration: {
        title: "Calibração da Mão",
        subtitle: "Mede o tamanho do seu dorso e dedos para precisão de porções",
        calibrate: "Iniciar Calibração",
      },
      deleteAccount: {
        title: "Excluir Conta",
        warning:
          "Esta ação é irreversível. Todos os seus dados e histórico serão apagados permanentemente.",
        confirmButton: "Sim, Excluir Minha Conta",
      },
    },
    search: {
      title: "Buscar Alimento",
      placeholder: "Digite o alimento ou prato...",
      aiSearch: "Busca Inteligente por IA",
      recent: "Buscas Recentes",
    },
    scanner: {
      title: "Scanner Nutricional",
      instructions: "Aponte a câmera para o prato ou alimento",
      takePhoto: "Tirar Foto",
      gallery: "Galeria",
    },
    chat: {
      title: "Nutricionista IA",
      placeholder: "Pergunte ao seu nutricionista...",
      send: "Enviar",
      welcome:
        "Olá! Sou seu Nutricionista IA. Como posso ajudar com sua dieta, refeições ou metas hoje?",
    },
  },
  en: {
    common: {
      appName: "NutriScan AI",
      loading: "Loading...",
      save: "Save",
      cancel: "Cancel",
      confirm: "Confirm",
      error: "Error",
      success: "Success",
      back: "Back",
      close: "Close",
    },
    nav: {
      scanner: "Scanner",
      search: "Search",
      shop: "Shop",
      profile: "Profile",
      chat: "Nutritionist",
    },
    auth: {
      loginTitle: "Sign in to your account",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "Your password",
      loginButton: "Sign In",
    },
    home: {
      greeting: "Hello",
      dailyGoal: "Daily Goal",
      caloriesEaten: "Eaten",
      caloriesBurned: "Burned",
      remaining: "Remaining",
      protein: "Protein",
      carbs: "Carbs",
      fats: "Fats",
      water: "Water",
      recentMeals: "Recent Meals",
      quickScan: "Scan Dish",
      quickSearch: "Search Food",
      aiCoach: "Chat with AI Nutritionist",
    },
    shop: {
      title: "Shop & Premium Plans",
      subtitle: "Unlock the full power of AI nutrition intelligence",
      weekly: "Weekly Plan",
      monthly: "Monthly Plan",
      yearly: "Yearly Plan",
      activePlan: "Current Plan",
      subscribeNow: "Subscribe Now",
      featuresTitle: "Exclusive Benefits",
      f1: "Unlimited AI nutrition scans",
      f2: "High-precision biometric hand calibration",
      f3: "Unlimited 24/7 AI Nutritionist chat",
      f4: "Advanced reports and detailed charts",
      cycleWeekly: "/week",
      cycleMonthly: "/month",
      cycleYearly: "/year",
      hintWeekly: "Ideal to try out",
      hintMonthly: "Most popular",
      hintYearly: "Save ~58%",
      badgePopular: "Popular",
      badgeBestValue: "Best Value",
      creditsTitle: "Extra Scan Pack",
      creditsSub: "Need more scans without subscribing? Get instant credits.",
      buyCredits: "Buy 50 Scans",
      mySubscription: "Your Premium Subscription",
      activeStatus: "Active",
      cancelSub: "Cancel Subscription",
      restorePurchases: "Restore Purchases",
      faqTitle: "Frequently Asked Questions",
    },
    profile: {
      title: "Profile",
      editProfile: "Edit Profile",
      adminPanel: "Admin Panel",
      subscriptions: "Subscriptions",
      rewards: "Rewards",
      history: "Reading History",
      goals: "Daily Goals",
      objective: "Objective",
      physicalData: "Physical Data",
      handCalibration: "Hand Calibration (High Precision)",
      changePassword: "Change Password",
      notifications: "Push Notifications",
      notificationsSub: "Enable alerts and daily reminders",
      privacy: "Rights & Privacy",
      deleteAccount: "Delete Account",
      signOut: "Sign Out",
      language: "App Language",
      sectionSubscription: "Subscription & History",
      sectionGoals: "Goals & Physical Data",
      sectionPreferences: "Preferences & Reminders",
      sectionSecurity: "Security & Account",
    },
    waterReminder: {
      title: "Hydration Reminders",
      subtitle: "Daily notifications to drink water and boost metabolism",
      active: "Enable Reminders",
      addTime: "Add Time",
      savedTimes: "Scheduled Times",
      notificationTitle: "Time to drink water! 💧",
      notificationBody: "Keep your body hydrated to boost your metabolism and burn fat.",
    },
    direitos: {
      title: "Rights & Privacy",
      termsTab: "Terms of Use",
      privacyTab: "Privacy Policy",
      copyLink: "Copy Link",
      copied: "Copied!",
      rightsTitle: "Terms of Use & General Conditions",
      privacyTitle: "Privacy Policy & Data Protection",
    },
    editProfile: {
      title: "Edit Profile",
      name: "Full name",
      email: "Email",
      save: "Save Changes",
      success: "Profile successfully updated",
    },
    subpages: {
      changePassword: {
        title: "Change Password",
        cardTitle: "Account Security",
        cardSub: "Use at least 6 characters",
        current: "Current password",
        new: "New password",
        confirm: "Confirm new password",
        button: "Update Password",
      },
      rewards: {
        title: "Bonus Rewards",
        subtitle: "Scans and credits sent by administrator",
        claim: "Claim Reward",
        claimed: "Claimed",
        empty: "No rewards available at the moment.",
      },
      subscriptions: {
        title: "Subscriptions",
        subtitle: "Manage your current plan and premium access",
        active: "Active Plan",
        upgrade: "Upgrade to Premium",
      },
      goals: {
        title: "Daily Goals",
        calories: "Daily Calories (kcal)",
        protein: "Protein (g)",
        carbs: "Carbs (g)",
        fats: "Fats (g)",
        save: "Save Goals",
      },
      objective: {
        title: "Your Objective",
        lose: "Lose Weight",
        maintain: "Maintain Weight",
        gain: "Gain Muscle Mass",
      },
      physicalData: {
        title: "Physical Data",
        weight: "Weight (kg)",
        height: "Height (cm)",
        age: "Age (years)",
        save: "Save Data",
      },
      handCalibration: {
        title: "Hand Calibration",
        subtitle: "Measures hand back and fingers for portion precision",
        calibrate: "Start Calibration",
      },
      deleteAccount: {
        title: "Delete Account",
        warning:
          "This action is irreversible. All your data and history will be permanently deleted.",
        confirmButton: "Yes, Delete My Account",
      },
    },
    search: {
      title: "Search Food",
      placeholder: "Type food or dish...",
      aiSearch: "AI Smart Search",
      recent: "Recent Searches",
    },
    scanner: {
      title: "Nutrition Scanner",
      instructions: "Point camera at food or dish",
      takePhoto: "Take Photo",
      gallery: "Gallery",
    },
    chat: {
      title: "AI Nutritionist",
      placeholder: "Ask your nutritionist...",
      send: "Send",
      welcome:
        "Hello! I am your AI Nutritionist. How can I help with your diet, meals, or goals today?",
    },
  },
  es: {
    common: {
      appName: "NutriScan AI",
      loading: "Cargando...",
      save: "Guardar",
      cancel: "Cancelar",
      confirm: "Confirmar",
      error: "Error",
      success: "Éxito",
      back: "Volver",
      close: "Cerrar",
    },
    nav: {
      scanner: "Escáner",
      search: "Buscar",
      shop: "Tienda",
      profile: "Perfil",
      chat: "Nutricionista",
    },
    auth: {
      loginTitle: "Iniciar sesión",
      emailPlaceholder: "tu@email.com",
      passwordPlaceholder: "Tu contraseña",
      loginButton: "Entrar",
    },
    home: {
      greeting: "Hola",
      dailyGoal: "Meta Diaria",
      caloriesEaten: "Consumidas",
      caloriesBurned: "Gastadas",
      remaining: "Restantes",
      protein: "Proteínas",
      carbs: "Carbohidratos",
      fats: "Grasas",
      water: "Agua",
      recentMeals: "Comidas Recientes",
      quickScan: "Escanear Plato",
      quickSearch: "Buscar Alimento",
      aiCoach: "Hablar con Nutricionista IA",
    },
    shop: {
      title: "Tienda y Planes Premium",
      subtitle: "Desbloquea todo el poder de la inteligencia artificial nutricional",
      weekly: "Plan Semanal",
      monthly: "Plan Mensual",
      yearly: "Plan Anual",
      activePlan: "Plan Actual",
      subscribeNow: "Suscribirse Ahora",
      featuresTitle: "Ventajas Exclusivas",
      f1: "Scans nutricionales ilimitados por IA",
      f2: "Calibración biométrica de mano de alta precisión",
      f3: "Chat ilimitado con Nutricionista IA 24/7",
      f4: "Informes avanzados y gráficos detallados",
      cycleWeekly: "/semana",
      cycleMonthly: "/mes",
      cycleYearly: "/año",
      hintWeekly: "Ideal para probar",
      hintMonthly: "Más elegido",
      hintYearly: "Ahorra ~58%",
      badgePopular: "Popular",
      badgeBestValue: "Mejor valor",
      creditsTitle: "Paquete Extra de Scans",
      creditsSub: "¿Necesitas más scans sin suscribirte? Obtén créditos instantáneos.",
      buyCredits: "Comprar 50 Scans",
      mySubscription: "Tu Suscripción Premium",
      activeStatus: "Activa",
      cancelSub: "Cancelar Suscripción",
      restorePurchases: "Restaurar Compras",
      faqTitle: "Preguntas Frecuentes",
    },
    profile: {
      title: "Perfil",
      editProfile: "Editar Perfil",
      adminPanel: "Panel de Administración",
      subscriptions: "Suscripciones",
      rewards: "Recompensas",
      history: "Historial de Lectura",
      goals: "Metas Diarias",
      objective: "Objetivo",
      physicalData: "Datos Físicos",
      handCalibration: "Calibración de Mano (Alta Precisión)",
      changePassword: "Cambiar Contraseña",
      notifications: "Notificaciones Push",
      notificationsSub: "Activar alertas y recordatorios diarios",
      privacy: "Derechos y Privacidad",
      deleteAccount: "Eliminar Cuenta",
      signOut: "Cerrar Sesión",
      language: "Idioma de la Aplicación",
      sectionSubscription: "Suscripción e Historial",
      sectionGoals: "Metas y Datos Físicos",
      sectionPreferences: "Preferencias y Recordatorios",
      sectionSecurity: "Seguridad y Cuenta",
    },
    waterReminder: {
      title: "Recordatorios de Hidratación",
      subtitle: "Notificaciones diarias para beber agua y acelerar el metabolismo",
      active: "Activar Recordatorios",
      addTime: "Añadir Hora",
      savedTimes: "Horarios Programados",
      notificationTitle: "¡Hora de beber agua! 💧",
      notificationBody: "Mantén tu cuerpo hidratado para acelerar tu metabolismo y quemar grasa.",
    },
    direitos: {
      title: "Derechos y Privacidad",
      termsTab: "Términos de Uso",
      privacyTab: "Política de Privacidad",
      copyLink: "Copiar Enlace",
      copied: "¡Copiado!",
      rightsTitle: "Términos de Uso y Condiciones Generales",
      privacyTitle: "Política de Privacidad y Protección de Datos",
    },
    editProfile: {
      title: "Editar Perfil",
      name: "Nombre completo",
      email: "Correo electrónico",
      save: "Guardar Cambios",
      success: "Perfil actualizado com éxito",
    },
    subpages: {
      changePassword: {
        title: "Cambiar Contraseña",
        cardTitle: "Seguridad de la cuenta",
        cardSub: "Usa al menos 6 caracteres",
        current: "Contraseña actual",
        new: "Nueva contraseña",
        confirm: "Confirmar nueva contraseña",
        button: "Actualizar Contraseña",
      },
      rewards: {
        title: "Recompensas de Bonus",
        subtitle: "Scans y créditos enviados por el administrador",
        claim: "Reclamar Recompensa",
        claimed: "Reclamado",
        empty: "No hay recompensas disponibles en este momento.",
      },
      subscriptions: {
        title: "Suscripciones",
        subtitle: "Gestiona tu plan actual y acceso premium",
        active: "Plan Activo",
        upgrade: "Cambiar a Premium",
      },
      goals: {
        title: "Metas Diarias",
        calories: "Calorías Diarias (kcal)",
        protein: "Proteínas (g)",
        carbs: "Carbohidratos (g)",
        fats: "Grasas (g)",
        save: "Guardar Metas",
      },
      objective: {
        title: "Tu Objetivo",
        lose: "Perder Peso",
        maintain: "Mantener Peso",
        gain: "Ganar Masa Muscular",
      },
      physicalData: {
        title: "Datos Físicos",
        weight: "Peso (kg)",
        height: "Altura (cm)",
        age: "Edad (años)",
        save: "Guardar Datos",
      },
      handCalibration: {
        title: "Calibración de Mano",
        subtitle: "Mide el dorso y dedos para precisión de porciones",
        calibrate: "Iniciar Calibración",
      },
      deleteAccount: {
        title: "Eliminar Cuenta",
        warning:
          "Esta acción es irreversible. Todos tus datos e historial serán eliminados permanentemente.",
        confirmButton: "Sí, Eliminar Mi Cuenta",
      },
    },
    search: {
      title: "Buscar Alimento",
      placeholder: "Escribe alimento o plato...",
      aiSearch: "Búsqueda Inteligente por IA",
      recent: "Búsquedas Recientes",
    },
    scanner: {
      title: "Scanner Nutricional",
      instructions: "Apunta la cámara al plato o alimento",
      takePhoto: "Tomar Foto",
      gallery: "Galería",
    },
    chat: {
      title: "Nutricionista IA",
      placeholder: "Pregunta a tu nutricionista...",
      send: "Enviar",
      welcome:
        "¡Hola! Soy tu Nutricionista IA. ¿Cómo puedo ayudarte con tu dieta, comidas o metas hoy?",
    },
  },
};

export type Language = "pt" | "en" | "es";

export function getCurrentLanguage(): Language {
  if (typeof window === "undefined") return "pt";
  const saved = localStorage.getItem("app_language") as Language;
  if (saved && ["pt", "en", "es"].includes(saved)) return saved;
  return "pt";
}

export function setAppLanguage(lang: Language) {
  if (typeof window === "undefined") return;
  localStorage.setItem("app_language", lang);
  window.dispatchEvent(new Event("languagechange"));
}

export function useTranslation() {
  const [lang, setLang] = useState<Language>(getCurrentLanguage);

  useEffect(() => {
    const handleLangChange = () => {
      setLang(getCurrentLanguage());
    };
    window.addEventListener("languagechange", handleLangChange);
    return () => window.removeEventListener("languagechange", handleLangChange);
  }, []);

  const t = (path: string): string => {
    const keys = path.split(".");
    let current: any = translations[lang] || translations.pt;
    for (const key of keys) {
      if (current && typeof current === "object" && key in current) {
        current = current[key];
      } else {
        return path;
      }
    }
    return typeof current === "string" ? current : path;
  };

  return { t, lang, setLanguage: setAppLanguage };
}
