/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PoliticaRouteImport } from './routes/politica'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DireitosPrivacidadeRouteImport } from './routes/direitos-privacidade'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppScannerRouteImport } from './routes/_app/scanner'
import { Route as AppPremiumRouteImport } from './routes/_app/premium'
import { Route as AppDiarioRouteImport } from './routes/_app/diario'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppBuscarRouteImport } from './routes/_app/buscar'
import { Route as AppPerfilIndexRouteImport } from './routes/_app/perfil/index'
import { Route as AppPerfilRecompensasRouteImport } from './routes/_app/perfil/recompensas'
import { Route as AppPerfilObjetivoRouteImport } from './routes/_app/perfil/objetivo'
import { Route as AppPerfilMetasRouteImport } from './routes/_app/perfil/metas'
import { Route as AppPerfilExcluirContaRouteImport } from './routes/_app/perfil/excluir-conta'
import { Route as AppPerfilEditarRouteImport } from './routes/_app/perfil/editar'
import { Route as AppPerfilDadosFisicosRouteImport } from './routes/_app/perfil/dados-fisicos'
import { Route as AppPerfilAlterarSenhaRouteImport } from './routes/_app/perfil/alterar-senha'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaRoute = PoliticaRouteImport.update({
  id: '/politica',
  path: '/politica',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitosPrivacidadeRoute = DireitosPrivacidadeRouteImport.update({
  id: '/direitos-privacidade',
  path: '/direitos-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppDiarioRoute = AppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilIndexRoute = AppPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRecompensasRoute = AppPerfilRecompensasRouteImport.update({
  id: '/perfil/recompensas',
  path: '/perfil/recompensas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilObjetivoRoute = AppPerfilObjetivoRouteImport.update({
  id: '/perfil/objetivo',
  path: '/perfil/objetivo',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilMetasRoute = AppPerfilMetasRouteImport.update({
  id: '/perfil/metas',
  path: '/perfil/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilExcluirContaRoute = AppPerfilExcluirContaRouteImport.update({
  id: '/perfil/excluir-conta',
  path: '/perfil/excluir-conta',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilEditarRoute = AppPerfilEditarRouteImport.update({
  id: '/perfil/editar',
  path: '/perfil/editar',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilDadosFisicosRoute = AppPerfilDadosFisicosRouteImport.update({
  id: '/perfil/dados-fisicos',
  path: '/perfil/dados-fisicos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilAlterarSenhaRoute = AppPerfilAlterarSenhaRouteImport.update({
  id: '/perfil/alterar-senha',
  path: '/perfil/alterar-senha',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/direitos-privacidade': typeof DireitosPrivacidadeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/politica': typeof PoliticaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/buscar': typeof AppBuscarRoute
  '/chat': typeof AppChatRoute
  '/diario': typeof AppDiarioRoute
  '/premium': typeof AppPremiumRoute
  '/scanner': typeof AppScannerRoute
  '/perfil/alterar-senha': typeof AppPerfilAlterarSenhaRoute
  '/perfil/dados-fisicos': typeof AppPerfilDadosFisicosRoute
  '/perfil/editar': typeof AppPerfilEditarRoute
  '/perfil/excluir-conta': typeof AppPerfilExcluirContaRoute
  '/perfil/metas': typeof AppPerfilMetasRoute
  '/perfil/objetivo': typeof AppPerfilObjetivoRoute
  '/perfil/recompensas': typeof AppPerfilRecompensasRoute
  '/perfil/': typeof AppPerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/direitos-privacidade': typeof DireitosPrivacidadeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/politica': typeof PoliticaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/buscar': typeof AppBuscarRoute
  '/chat': typeof AppChatRoute
  '/diario': typeof AppDiarioRoute
  '/premium': typeof AppPremiumRoute
  '/scanner': typeof AppScannerRoute
  '/perfil/alterar-senha': typeof AppPerfilAlterarSenhaRoute
  '/perfil/dados-fisicos': typeof AppPerfilDadosFisicosRoute
  '/perfil/editar': typeof AppPerfilEditarRoute
  '/perfil/excluir-conta': typeof AppPerfilExcluirContaRoute
  '/perfil/metas': typeof AppPerfilMetasRoute
  '/perfil/objetivo': typeof AppPerfilObjetivoRoute
  '/perfil/recompensas': typeof AppPerfilRecompensasRoute
  '/perfil': typeof AppPerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/direitos-privacidade': typeof DireitosPrivacidadeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/politica': typeof PoliticaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/_app/buscar': typeof AppBuscarRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/diario': typeof AppDiarioRoute
  '/_app/premium': typeof AppPremiumRoute
  '/_app/scanner': typeof AppScannerRoute
  '/_app/perfil/alterar-senha': typeof AppPerfilAlterarSenhaRoute
  '/_app/perfil/dados-fisicos': typeof AppPerfilDadosFisicosRoute
  '/_app/perfil/editar': typeof AppPerfilEditarRoute
  '/_app/perfil/excluir-conta': typeof AppPerfilExcluirContaRoute
  '/_app/perfil/metas': typeof AppPerfilMetasRoute
  '/_app/perfil/objetivo': typeof AppPerfilObjetivoRoute
  '/_app/perfil/recompensas': typeof AppPerfilRecompensasRoute
  '/_app/perfil/': typeof AppPerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/direitos-privacidade'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/politica'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/buscar'
    | '/chat'
    | '/diario'
    | '/premium'
    | '/scanner'
    | '/perfil/alterar-senha'
    | '/perfil/dados-fisicos'
    | '/perfil/editar'
    | '/perfil/excluir-conta'
    | '/perfil/metas'
    | '/perfil/objetivo'
    | '/perfil/recompensas'
    | '/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/direitos-privacidade'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/politica'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/buscar'
    | '/chat'
    | '/diario'
    | '/premium'
    | '/scanner'
    | '/perfil/alterar-senha'
    | '/perfil/dados-fisicos'
    | '/perfil/editar'
    | '/perfil/excluir-conta'
    | '/perfil/metas'
    | '/perfil/objetivo'
    | '/perfil/recompensas'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/direitos-privacidade'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/politica'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/_app/buscar'
    | '/_app/chat'
    | '/_app/diario'
    | '/_app/premium'
    | '/_app/scanner'
    | '/_app/perfil/alterar-senha'
    | '/_app/perfil/dados-fisicos'
    | '/_app/perfil/editar'
    | '/_app/perfil/excluir-conta'
    | '/_app/perfil/metas'
    | '/_app/perfil/objetivo'
    | '/_app/perfil/recompensas'
    | '/_app/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  DireitosPrivacidadeRoute: typeof DireitosPrivacidadeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PoliticaRoute: typeof PoliticaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica': {
      id: '/politica'
      path: '/politica'
      fullPath: '/politica'
      preLoaderRoute: typeof PoliticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direitos-privacidade': {
      id: '/direitos-privacidade'
      path: '/direitos-privacidade'
      fullPath: '/direitos-privacidade'
      preLoaderRoute: typeof DireitosPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/scanner': {
      id: '/_app/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/premium': {
      id: '/_app/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diario': {
      id: '/_app/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AppDiarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buscar': {
      id: '/_app/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/': {
      id: '/_app/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AppPerfilIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/recompensas': {
      id: '/_app/perfil/recompensas'
      path: '/perfil/recompensas'
      fullPath: '/perfil/recompensas'
      preLoaderRoute: typeof AppPerfilRecompensasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/objetivo': {
      id: '/_app/perfil/objetivo'
      path: '/perfil/objetivo'
      fullPath: '/perfil/objetivo'
      preLoaderRoute: typeof AppPerfilObjetivoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/metas': {
      id: '/_app/perfil/metas'
      path: '/perfil/metas'
      fullPath: '/perfil/metas'
      preLoaderRoute: typeof AppPerfilMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/excluir-conta': {
      id: '/_app/perfil/excluir-conta'
      path: '/perfil/excluir-conta'
      fullPath: '/perfil/excluir-conta'
      preLoaderRoute: typeof AppPerfilExcluirContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/editar': {
      id: '/_app/perfil/editar'
      path: '/perfil/editar'
      fullPath: '/perfil/editar'
      preLoaderRoute: typeof AppPerfilEditarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/dados-fisicos': {
      id: '/_app/perfil/dados-fisicos'
      path: '/perfil/dados-fisicos'
      fullPath: '/perfil/dados-fisicos'
      preLoaderRoute: typeof AppPerfilDadosFisicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/alterar-senha': {
      id: '/_app/perfil/alterar-senha'
      path: '/perfil/alterar-senha'
      fullPath: '/perfil/alterar-senha'
      preLoaderRoute: typeof AppPerfilAlterarSenhaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuscarRoute: typeof AppBuscarRoute
  AppChatRoute: typeof AppChatRoute
  AppDiarioRoute: typeof AppDiarioRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppScannerRoute: typeof AppScannerRoute
  AppPerfilAlterarSenhaRoute: typeof AppPerfilAlterarSenhaRoute
  AppPerfilDadosFisicosRoute: typeof AppPerfilDadosFisicosRoute
  AppPerfilEditarRoute: typeof AppPerfilEditarRoute
  AppPerfilExcluirContaRoute: typeof AppPerfilExcluirContaRoute
  AppPerfilMetasRoute: typeof AppPerfilMetasRoute
  AppPerfilObjetivoRoute: typeof AppPerfilObjetivoRoute
  AppPerfilRecompensasRoute: typeof AppPerfilRecompensasRoute
  AppPerfilIndexRoute: typeof AppPerfilIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuscarRoute: AppBuscarRoute,
  AppChatRoute: AppChatRoute,
  AppDiarioRoute: AppDiarioRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppScannerRoute: AppScannerRoute,
  AppPerfilAlterarSenhaRoute: AppPerfilAlterarSenhaRoute,
  AppPerfilDadosFisicosRoute: AppPerfilDadosFisicosRoute,
  AppPerfilEditarRoute: AppPerfilEditarRoute,
  AppPerfilExcluirContaRoute: AppPerfilExcluirContaRoute,
  AppPerfilMetasRoute: AppPerfilMetasRoute,
  AppPerfilObjetivoRoute: AppPerfilObjetivoRoute,
  AppPerfilRecompensasRoute: AppPerfilRecompensasRoute,
  AppPerfilIndexRoute: AppPerfilIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  DireitosPrivacidadeRoute: DireitosPrivacidadeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PoliticaRoute: PoliticaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
